'use strict';
const AMMO={normal:{name:'实心弹',short:'实',color:'#dae9ec'},heavy:{name:'爆破弹',short:'爆',color:'#ffc571'},pierce:{name:'穿甲弹',short:'穿',color:'#a4dcf4'},cluster:{name:'子母弹',short:'母',color:'#ffafdc'},frost:{name:'霜冻弹',short:'霜',color:'#a4f6fb'},acid:{name:'腐蚀弹',short:'蚀',color:'#bcf17f'},arc:{name:'电弧弹',short:'电',color:'#d1b2ff'}};
const MAPS={
fjord:{name:'冰海峡湾',rule:'低矮山丘 · 标准重力',gravity:420,wind:0,hp:1,hills:[[540,120,80],[1060,140,80]],sky:['#89d9ee','#d2eeec'],water:'#59b6c4',rock:'#2b6071',accent:'#b8edf0'},
dunes:{name:'风蚀沙海',rule:'稳定东风 → 28 · 双方炮弹受风影响',gravity:420,wind:28,hp:1,hills:[[560,80,85],[1040,100,85]],sky:['#eab783','#f5ddba'],water:'#c18d52',rock:'#926342',accent:'#efc58b'},
volcano:{name:'熔岩裂谷',rule:'高山隘口 · 岩层耐久 1.4',gravity:420,wind:0,hp:1.4,hills:[[560,300,70],[1040,380,70]],sky:['#49394f','#bd7769'],water:'#e17c3c',rock:'#514556',accent:'#df966c'},
moon:{name:'月面遗迹',rule:'重力 78% · 弹道更平、滞空更久',gravity:327.6,wind:0,hp:.8,hills:[[540,180,80],[1080,160,80]],sky:['#233449','#667ca0'],water:'#647b91',rock:'#526377',accent:'#adc3d2'},
forest:{name:'荧光丛林',rule:'浮岩掩体 · 寻找上下射击窗口',gravity:420,wind:0,hp:1,rects:[[500,380,120,40],[920,260,180,40],[1080,620,60,160]],sky:['#254d56','#78ada0'],water:'#3f8f82',rock:'#305e5d',accent:'#b5e18e'}
};
const V={inventory:{},map:MAPS.fjord,mapId:'fjord',bag:[],lastMap:null,generation:0,serial:0,loot:new Set(),rewarded:false,volley:0,shards:0,arcs:0,arcTargets:new Set(),frozen:false,immune:false,freezeVolley:-1,enemyAction:false,totalEarned:0,spent:0};
const vReset=reset,vEncounter=encounter,vTerrain=newTerrain,vFire=fire,vSplit=split,vImpact=impact,vBreak=breakBlock,vCollapse=collapse,vModules=inspectModules,vVictory=victory,vStep=step,vHUD=updateHUD,vBlock=block,vRender=render;
function mapWind(){return V.map?.wind||0;}
function stockTotal(){return Object.values(V.inventory).reduce((a,b)=>a+b,0);}
function pickAmmo(){const weights=[['heavy',30],['pierce',25],['cluster',15],['frost',10],['acid',12],['arc',8]];let n=Math.random()*100;for(const [key,w] of weights){n-=w;if(n<0)return key;}return'heavy';}
function earnAmmo(type,n,why){const room=Math.max(0,Math.min(6-(V.inventory[type]||0),16-stockTotal())),got=Math.min(n,room);V.inventory[type]=(V.inventory[type]||0)+got;V.totalEarned+=got;const overflow=n-got;if(overflow)repair(S.player,overflow*2);toast(why+' · '+AMMO[type].name+' +'+got+(overflow?'（溢出转维修）':''));updateHUD();return got;}
function setMap(id){V.mapId=id;V.map=MAPS[id];V.lastMap=id;WORLD.g=V.map.gravity;S.previewCache=null;S.terrainRevision++;}
function nextMap(first=false){if(first)return'fjord';if(!V.bag.length){V.bag=Object.keys(MAPS).sort(()=>Math.random()-.5);if(V.bag[V.bag.length-1]===V.lastMap){const t=V.bag[0];V.bag[0]=V.bag[V.bag.length-1];V.bag[V.bag.length-1]=t;}}return V.bag.pop();}
newTerrain=function(){const map=V.map,blocks=[];if(map.rects){for(const [rx,ry,rw,rh] of map.rects)for(let x=rx;x<rx+rw;x+=20)for(let y=ry;y<ry+rh;y+=20)blocks.push({x,y,w:20,h:20,hp:map.hp,alive:true,terrain:true});}else for(let x=430;x<=1150;x+=20){const height=Math.max(0,...map.hills.map(([center,h,width])=>h*Math.exp(-(((x-center)/width)**2))));for(let y=778;y>778-height;y-=20)blocks.push({x,y:y-20,w:20,h:20,hp:map.hp,alive:true,terrain:true});}
V.generation++;const types=(R.active?R.stage===1:S.wave===1)?['acid','arc']:[pickAmmo(),pickAmmo()];const spots=[[420,550],[1175,400]];spots.forEach(([x,y],i)=>blocks.push({x,y,w:33,h:33,hp:1,alive:true,terrain:true,crate:true,ammoDrop:types[i],lootId:'crate:'+V.generation+':'+i}));return blocks;};
reset=function(mode=S.mode){V.inventory={heavy:2,pierce:2,cluster:1,frost:1,acid:0,arc:0};V.bag=[];V.generation=0;V.serial=0;V.loot.clear();V.rewarded=false;V.frozen=false;V.immune=false;V.totalEarned=0;V.spent=0;V.enemyAction=false;V.volley=0;V.freezeVolley=-1;V.shards=0;V.arcs=0;V.arcTargets.clear();const wanted=$('mapChoice').value||'auto';setMap(MODES[mode]?'fjord':wanted==='auto'?Object.keys(MAPS)[Math.floor(Math.random()*5)]:wanted);vReset(mode);S.ammo='normal';syncAmmo();};
encounter=function(){V.serial++;setMap(nextMap(R.stage===1));V.rewarded=false;V.frozen=false;V.immune=false;V.enemyAction=false;vEncounter();if(V.mapId==='moon'){aim(32);S.power=76;}else{aim(45);S.power=90;}$('power').value=S.power;$('powerValue').textContent=Math.round(S.power)+'%';syncAmmo();};
function setAmmo(type){if(type!=='normal'&&(V.inventory[type]||0)<=0){toast('尚无'+AMMO[type].name+' · 击碎补给箱获取');return;}S.ammo=type;syncAmmo();}
function syncAmmo(){document.querySelectorAll('.ammo').forEach(b=>{const key=b.dataset.ammo;b.classList.toggle('active',key===S.ammo);b.disabled=key!=='normal'&&!(V.inventory[key]>0);b.title=AMMO[key].name+(key==='normal'?' · 无限':' · 剩余 '+(V.inventory[key]||0));});document.querySelectorAll('[data-count]').forEach(b=>b.textContent=b.dataset.count==='normal'?'∞':V.inventory[b.dataset.count]||0);}
function specialStats(p){const scale=R.active?1+.25*level('powder')+(R.tempDamage||0):1;const specs={cluster:[.6,28],frost:[.55,38],acid:[.65,42],arc:[.8,18]};if(specs[p.ammo]){p.damage=scale*specs[p.ammo][0];p.radius=specs[p.ammo][1];}else if(!R.active){p.damage=1;p.radius=p.ammo==='heavy'?62:p.ammo==='pierce'?18:31;}p.v4Volley=V.volley;}
fire=function(side='player'){if(S.status!=='playing'||S.phase!=='aim')return false;if(side==='player'&&S.ammo!=='normal'&&!(V.inventory[S.ammo]>0)){setAmmo('normal');toast('弹药耗尽，已切换实心弹');return false;}if(side==='enemy'&&V.frozen){V.frozen=false;V.immune=true;R.volleySide='enemy';S.shotOwner='enemy';S.phase='aftermath';S.phaseTime=0;S.focusX=1370;toast('敌军冻结，本轮停火');return true;}const selected=S.ammo,startIndex=S.bullets.length,ok=vFire(side);if(!ok)return false;if(S.bullets.length>startIndex){V.volley++;V.shards=0;V.arcs=0;V.arcTargets.clear();for(const p of S.bullets.slice(startIndex)){p.v4Volley=V.volley;if(side==='player')specialStats(p);}if(side==='player'&&selected!=='normal'){V.inventory[selected]--;V.spent++;if(V.inventory[selected]===0){S.ammo='normal';toast(AMMO[selected].name+' 已用完，切回实心弹');}}if(side==='enemy')V.enemyAction=true;}syncAmmo();return ok;};
split=function(p,g){if(p.shard)return;const start=S.bullets.length;vSplit(p,g);for(const q of S.bullets.slice(start)){q.v4Volley=p.v4Volley;q.damage=p.damage;q.radius=p.radius;q.shard=!!p.shard;}};
breakBlock=function(b,p){if(b.crate&&p.side==='enemy')return;if(p.noLoot)b.noDrop=true;const was=b.alive;if(p.side==='player'&&!p.noLoot)b.lootEligible=true;let shot=p;if(b.corroded&&p.side==='player'&&(p.v4Volley??V.volley)>b.corroded)shot={...p,damage:(p.damage||1)*1.35};if(R.active)vBreak(b,shot);else if(b.alive){b.hp-=(shot.damage||1);if(b.hp<=0){b.alive=false;S.terrainRevision++;explode(b.x+b.w/2,b.y+b.h/2,b.terrain?V.map.accent:'#e8d6b8',4);if(shot.side==='player'){if(!b.terrain)S.destroyed++;S.score+=b.terrain?2:10*S.wave;}}}if(was&&!b.alive&&b.crate&&p.side==='player'&&!V.loot.has(b.lootId)){V.loot.add(b.lootId);earnAmmo(b.ammoDrop,1,'补给箱');}};
collapse=function(blocks,side){const before=blocks.filter(b=>b.alive);vCollapse(blocks,side);if(side==='player')for(const b of before)if(!b.alive&&!b.noDrop)b.lootEligible=true;};
inspectModules=function(){const fresh=R.modules.filter(m=>!m.disabled);vModules();const mapping={raider:'cluster',armor:'pierce',artillery:'heavy',workshop:'acid',titan:'arc',eclipse:'frost'};for(const m of fresh){const key='module:'+V.serial+':'+m.id;if(m.disabled&&m.cells.filter(b=>!b.alive&&b.lootEligible&&!b.noDrop).length>=2&&!V.loot.has(key)){V.loot.add(key);earnAmmo(mapping[R.enemy.id]||R.enemy.moduleDrops?.[m.id]||'pierce',1,'模块掉落');}}};
function applySpecial(b,p){p.hits++;const targets=b.terrain?S.terrain:S.enemy;let hit=targets.filter(q=>q.alive&&!p.hitIds.has(q)&&Math.hypot(q.x+q.w/2-p.x,q.y+q.h/2-p.y)<p.radius);if(!hit.includes(b)&&!p.hitIds.has(b))hit.push(b);for(const q of hit){p.hitIds.add(q);if(p.ammo==='acid'&&!q.terrain){q.armor=Math.max(0,(q.armor||0)-1);if(!q.corroded)q.corroded=p.v4Volley;}breakBlock(q,p);}explode(p.x,p.y,AMMO[p.ammo]?.color||'#ffd888',8);S.focusX=p.x;p.ttl=0;
if(p.ammo==='frost'&&!b.terrain&&!V.immune&&V.freezeVolley!==p.v4Volley){V.frozen=true;V.freezeVolley=p.v4Volley;toast('霜冻命中 · 敌方下一行动暂停');}
if(p.ammo==='cluster'&&!p.shard){const count=Math.min(3,24-V.shards);for(let i=0;i<count;i++){const a=-Math.PI*.8+i*.9;const q=projectile(p.x,p.y-8,Math.cos(a)*230,-Math.abs(Math.sin(a))*180,'player','shard');Object.assign(q,{damage:(p.damage/.6)*.35,radius:20,ttl:.8,passed:true,shard:true,v4Volley:p.v4Volley,maxHits:1});S.bullets.push(q);V.shards++;}}
if(p.ammo==='arc'&&!b.terrain){const possible=S.enemy.filter(q=>q.alive&&!p.hitIds.has(q)&&!V.arcTargets.has(q)&&Math.hypot(q.x+q.w/2-p.x,q.y+q.h/2-p.y)<=70).sort((a,b)=>(b.module?1:0)-(a.module?1:0));for(const q of possible.slice(0,Math.min(3,12-V.arcs))){V.arcTargets.add(q);V.arcs++;breakBlock(q,{...p,damage:(p.damage/.8)*.45});S.rings.push({x:q.x+q.w/2,y:q.y+q.h/2,r:4,life:.3,max:.3,color:'#d8bbff'});}}}
impact=function(b,p){if(p.side==='enemy'||!['cluster','frost','acid','arc','shard'].includes(p.ammo))return vImpact(b,p);if(R.active&&!b.terrain&&R.barrier>0)return vImpact(b,p);applySpecial(b,p);};
victory=function(){if(R.resolved)return;if(V.rewarded||R.stage>=MODES[R.mode].total)return vVictory();V.rewarded=true;const amount=R.enemy.boss||R.elite?3:2,types=Object.keys(AMMO).filter(k=>k!=='normal').sort(()=>Math.random()-.5).slice(0,3);choices('战利品：弹药补给','库存跨关保留，每类最多 6 发、总计 16 发；溢出转维修。',types.map(k=>({title:AMMO[k].name+' +'+amount,text:'当前 '+V.inventory[k]+' 发 · 本局已获得 '+V.totalEarned+' 发',action:()=>{earnAmmo(k,amount,'战后奖励');vVictory();}})));};
step=function(dt){const playing=S.status==='playing',before=S.phase,oldWave=S.wave;vStep(dt);if(playing&&V.enemyAction&&before==='flight'&&S.phase==='aftermath'){V.enemyAction=false;V.immune=false;}if(!R.active&&S.mode==='sandbox'&&S.wave!==oldWave){setMap(nextMap());S.terrain=newTerrain();earnAmmo(pickAmmo(),2,'试炮补给');}};
updateHUD=function(){vHUD();$('mapName').textContent=V.map.name;$('mapRule').textContent=V.map.rule;$('mapChoice').disabled=R.active;$('ammoTotal').textContent='特殊弹 '+stockTotal()+'/16';if(R.active&&V.frozen)$('intentText').textContent='冻结：下一次行动暂停';else if(R.active&&V.immune)$('intentText').textContent='解冻免疫 · 下一轮：'+(INTENTS[R.intent]||'炮击');syncAmmo();};
block=function(b){if(b.crate){const color=AMMO[b.ammoDrop].color;ctx.fillStyle='#364855';ctx.fillRect(b.x,b.y,b.w,b.h);ctx.fillStyle=color;ctx.fillRect(b.x+3,b.y+3,b.w-6,b.h-6);ctx.strokeStyle='#fff1b7';ctx.lineWidth=2;ctx.strokeRect(b.x,b.y,b.w,b.h);ctx.fillStyle='#263c45';ctx.font='bold 17px sans-serif';ctx.textAlign='center';ctx.fillText(AMMO[b.ammoDrop].short,b.x+b.w/2,b.y+23);return;}if(b.terrain){ctx.fillStyle=V.map.rock;ctx.fillRect(b.x,b.y,b.w+.4,b.h+.4);if(!terrainCells.has(b.x+','+(b.y-20))){ctx.fillStyle=V.map.accent;ctx.fillRect(b.x,b.y,b.w,3);}ctx.fillStyle='#ffffff0a';ctx.fillRect(b.x,b.y,3,b.h);return;}vBlock(b);if(b.corroded){ctx.strokeStyle='#b8f179';ctx.lineWidth=2;ctx.strokeRect(b.x+3,b.y+3,b.w-6,b.h-6);}};
background=function(){terrainCells=new Set(S.terrain.filter(b=>b.alive).map(b=>b.x+','+b.y));const map=V.map,gradient=ctx.createLinearGradient(0,0,0,900);gradient.addColorStop(0,map.sky[0]);gradient.addColorStop(1,map.sky[1]);ctx.fillStyle=gradient;ctx.fillRect(S.camera,0,viewW,900);if(V.mapId==='moon'){ctx.fillStyle='#ddeaffaa';for(let i=0;i<75;i++){let x=(i*137)%1600,y=40+(i*67)%370;ctx.fillRect(x,y,2,2);}ctx.fillStyle='#d0dbe599';ctx.beginPath();ctx.arc(900,170,46,0,7);ctx.fill();}else{ctx.fillStyle='#ffffff26';for(let i=0;i<8;i++){ctx.beginPath();ctx.ellipse(i*230,150+i%3*58,70,17,0,0,7);ctx.fill();}}for(let layer=0;layer<3;layer++){const pts=[[0,788]];for(let x=0;x<=1700;x+=65)pts.push([x,590+layer*44-Math.abs(Math.sin(x*.009+layer*2))*120]);pts.push([1700,788]);ctx.globalAlpha=.2+layer*.12;poly(pts,map.rock);ctx.globalAlpha=1;}ctx.fillStyle=map.water;ctx.fillRect(0,784,1600,116);ctx.strokeStyle=map.accent;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,786);ctx.lineTo(1600,786);ctx.stroke();ctx.globalAlpha=.35;for(let i=0;i<22;i++){const x=(i*113+S.time*9)%1650;ctx.beginPath();ctx.moveTo(x,807+i%5*17);ctx.lineTo(x+30+randStable(i)*25,807+i%5*17);ctx.stroke();}ctx.globalAlpha=1;for(const b of S.terrain)if(b.alive)block(b);};
render=function(dt){vRender(dt);for(const p of S.bullets){if(AMMO[p.ammo]&&p.ammo!=='normal'){ctx.fillStyle=AMMO[p.ammo].color;ctx.beginPath();ctx.arc(p.x,p.y,3.5,0,Math.PI*2);ctx.fill();}}if(V.frozen){ctx.strokeStyle='#9df4ff';ctx.lineWidth=3;for(const b of S.enemy.filter(b=>b.alive&&b.col%3===0)){ctx.strokeRect(b.x,b.y,b.w,b.h);}}};
$('mapChoice').onchange=()=>{if(!R.active)reset(S.mode);};document.querySelectorAll('.ammo').forEach(b=>b.onclick=()=>setAmmo(b.dataset.ammo));Object.assign(window.siege,{start,fire,pause,reset});window.siege.supply={state:()=>({map:V.mapId,gravity:WORLD.g,wind:mapWind(),inventory:{...V.inventory},total:stockTotal(),earned:V.totalEarned,spent:V.spent,frozen:V.frozen,immune:V.immune}),select:setAmmo};
reset('expedition');
