'use strict';
// Expedition rules and builds designed with GPT-6 Astra. Pure local game state.
const MODES={expedition:{name:'九城远征',total:9},endless:{name:'无尽围城',total:Infinity},bossrush:{name:'首领连战',total:3},survival:{name:'七分钟突围',total:5}};
const CARDS=[
{id:'powder',name:'浓缩火药',family:'爆破',max:3,text:'所有炮弹伤害 +25%',icon:'✹'},
{id:'blast',name:'广域爆破',family:'爆破',max:2,text:'爆破弹爆炸半径 +12',icon:'◎'},
{id:'echo',name:'余震引信',family:'爆破',max:1,text:'爆破命中追加小型爆炸，每炮最多 6 次',icon:'✦'},
{id:'prism',name:'分裂棱镜',family:'增殖',max:2,text:'穿门后额外生成 3 枚炮弹',icon:'⟁'},
{id:'focus',name:'蜂群校准',family:'增殖',max:2,text:'分裂散射减少 30%，弹幕更集中',icon:'⊕'},
{id:'overload',name:'门后超载',family:'增殖',max:2,text:'穿过基础 ×10 / ×20 门，伤害 +20%',icon:'ϟ'},
{id:'tungsten',name:'钨钢弹芯',family:'穿甲',max:3,text:'穿甲弹伤害 +40%，直接绕过装甲',icon:'◆'},
{id:'drill',name:'地层钻头',family:'穿甲',max:2,text:'穿透次数 +2，穿山不消耗次数',icon:'➤'},
{id:'weakness',name:'弱点解析',family:'穿甲',max:1,text:'穿甲弹对发光弱点造成双倍伤害',icon:'⌖'},
{id:'engineer',name:'野战工兵',family:'守城',max:3,text:'每场胜利额外修复 6 块城墙',icon:'⚒'},
{id:'guard',name:'城防护幕',family:'守城',max:2,text:'应急护盾额外拦截 2 枚敌弹',icon:'◇'},
{id:'salvage',name:'废墟回收',family:'守城',max:2,text:'每摧毁 10 块敌堡修复 1 块，每炮最多 5 块',icon:'♻'}];
const ENEMIES={
raider:{name:'掠夺双炮',tag:'副炮',color:'#ffb35c',hp:.85,rows:9,cols:7,pattern:['single','double'],trait:'击破橙色副炮，永久关闭双发'},
armor:{name:'铁甲卫城',tag:'铆钉',color:'#61d9ee',hp:1,rows:11,cols:7,pattern:['single','single','heavy'],armor:1.2,trait:'穿甲弹绕过装甲；击破铆钉使装甲脱落'},
artillery:{name:'赤焰重炮',tag:'火药库',color:'#ff7261',hp:.95,rows:11,cols:7,pattern:['charge','heavy'],trait:'击破红色火药库，打断蓄力轰炸'},
workshop:{name:'修补工坊',tag:'维修核',color:'#8fe19a',hp:1.05,rows:10,cols:7,pattern:['single'],trait:'每轮修复 5 块，最多 3 次；击破绿核阻止修复'},
titan:{name:'铁壁巨像',tag:'动力炉',color:'#ffae50',hp:2.1,rows:12,cols:9,boss:true,armor:1.5,pattern:['single','charge','doubleHeavy'],trait:'击破橙色动力炉，卸除装甲并令首领停火'},
eclipse:{name:'吞日核心',tag:'蓄能器',color:'#d5a0ff',hp:2.8,rows:14,cols:9,boss:true,pattern:['single','charge','meteor'],trait:'拆掉两侧紫色蓄能器，关闭屏障并打断陨火'}
};
const INTENTS={single:'实心炮击',double:'双炮齐射',heavy:'重炮轰炸',charge:'蓄力 · 本轮不攻击',doubleHeavy:'双重爆破',meteor:'三重陨火',skip:'模块瘫痪 · 本轮停火'};
const R={active:false,mode:'expedition',stage:1,cards:{},enemy:null,elite:false,modules:[],enemyTurn:0,intent:'single',guardUsed:false,guardHits:0,barrier:0,nextElite:false,noGuard:false,extraReward:0,resolved:false,volley:0,volleySide:null,enemySpawned:0,budget:4,aftershocks:[],echoUsed:0,salvageCount:0,salvageRepaired:0,enemyRepairs:0,phase2:false,disabled:false,skip:false,record:0,choiceToken:0,cleared:0,challengeTime:0};
const level=id=>R.cards[id]||0;
const oldReset=reset,oldStart=start,oldFire=fire,oldStep=step,oldImpact=impact,oldBreak=breakBlock,oldCollapse=collapse,oldSplit=split,oldCamera=cameraStep,oldHUD=updateHUD,oldFinish=finish,oldUpgrade=upgrade,oldBlock=block,oldCastleDraw=drawCastle,oldGatesDraw=drawGates;
const alive=(bs)=>bs.filter(b=>b.alive).length;
function repair(bs,n){let restored=0;for(const b of [...bs].sort((a,b)=>a.row-b.row)){if(restored>=n)break;if(b.alive)continue;const supported=b.row===0||bs.some(q=>q.alive&&Math.abs(q.col-b.col)+Math.abs(q.row-b.row)===1);if(!supported)continue;b.alive=true;b.hp=b.maxHp||1;restored++;}if(restored)S.terrainRevision++;return restored;}
function damageValue(p,b){let d=p.damage||1;if(p.side==='player'){if(p.ammo==='pierce'&&b.module&&level('weakness'))d*=2;if(R.enemy?.id==='eclipse'&&R.modules.every(m=>m.disabled))d*=1.35;}return d;}
function buildEnemy(id,elite=false){const spec=ENEMIES[id],hp=spec.boss?spec.hp:(1+.15*(R.stage-1))*spec.hp;R.enemy={...spec,id};R.elite=elite;R.budget=spec.boss?8:elite?6:4;const cols=spec.cols,rows=spec.rows,base=1250,blocks=[];for(let col=0;col<cols;col++){const height=rows+((col<2||col>=cols-2)?2:0);for(let row=0;row<height;row++){if(row===height-1&&col%2)continue;let maxHp=hp*(elite?1.35:1)*(R.mode==='bossrush'&&R.stage===3?1.3:1)*(R.mode==='endless'?1+Math.max(0,R.stage-5)*.06:1);blocks.push({x:base+col*23,y:752-(row+1)*22,w:22,h:21,col,row,side:'enemy',alive:true,hp:maxHp,maxHp,armor:col<2?(spec.armor||0):0,roof:(col===0||col===cols-1)&&row===height-1});}}
R.modules=[];const configs=id==='eclipse'?[{col:0,row:rows-3},{col:cols-2,row:rows-3}]:[{col:id==='titan'?0:2,row:id==='titan'?2:Math.min(5,rows-3)}];configs.forEach((pos,index)=>{const cells=blocks.filter(b=>b.col>=pos.col&&b.col<pos.col+2&&b.row>=pos.row&&b.row<pos.row+2);const mod={id:index,name:spec.tag,cells,disabled:false};for(const b of cells)b.module=index+1;R.modules.push(mod);});S.enemy=blocks;R.enemyTurn=0;R.enemyRepairs=0;R.phase2=false;R.disabled=false;R.skip=false;R.barrier=id==='eclipse'?3:0;R.intent=spec.pattern[0];}
function chooseEnemy(){if(R.mode==='bossrush')return R.stage===1?'titan':'eclipse';if(R.mode==='survival'&&R.stage===5)return'titan';if(R.mode==='expedition'&&R.stage===3)return'titan';if(R.mode==='expedition'&&R.stage===9)return'eclipse';if(R.mode==='endless'&&R.stage%5===0)return R.stage%10===0?'eclipse':'titan';const ordinary=['raider','armor','artillery','workshop'];return ordinary[(R.stage-1)%4];}
function encounter(){S.wave=R.stage;S.mode=R.mode;S.enemy=[];S.terrain=newTerrain();S.terrainRevision++;S.gates=makeGates();S.previewCache=null;S.bullets=[];S.chunks=[];S.particles=[];S.smoke=[];S.rings=[];S.labels=[];S.transition=0;S.phase='aim';S.phaseTime=0;S.camera=0;S.focusX=220;S.nextOwner='player';S.shotOwner=null;S.cooldown=0;R.resolved=false;R.guardUsed=R.noGuard;R.guardHits=0;R.noGuard=false;R.aftershocks=[];R.volleySide=null;buildEnemy(chooseEnemy(),R.nextElite||(R.mode==='expedition'&&R.stage===6)||(R.mode==='endless'&&R.stage%5===3));R.extraReward=R.nextElite?1:0;R.nextElite=false;S.status='playing';$('overlay').classList.add('hidden');toast((R.enemy.boss?'首领来袭：':'第 '+R.stage+' 城 · ')+R.enemy.name);updateHUD();}
function clearExtras(){R.aftershocks=[];R.guardHits=0;R.barrier=0;R.choiceToken++;$('enemyIntent').hidden=true;$('runControls').hidden=true;}
reset=function(mode=S.mode){clearExtras();R.active=!!MODES[mode];if(!R.active){R.enemy=null;R.modules=[];oldReset(mode);return;}R.mode=mode;R.stage=1;R.cards={};R.tempDamage=0;R.enemy=null;R.modules=[];R.cleared=0;R.nextElite=false;R.noGuard=false;R.resolved=false;R.challengeTime=0;R.record=0;try{R.record=Number(localStorage.getItem('siege-best-'+mode)||0);}catch{}oldReset('classic');S.mode=mode;buildEnemy('raider',false);S.player.forEach(b=>b.maxHp=1);$('modeLabel').textContent=MODES[mode].name;document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('enemyIntent').hidden=false;$('runControls').hidden=false;showOverlay(MODES[mode].name,mode==='bossrush'?'先选择六项升级，再挑战三场首领战。':mode==='survival'?'在 420 秒内攻破五城，最后一战迎战铁壁巨像。':'每战选择升级，探索岔路，击破敌堡弱点。构筑只在本局保留。',mode==='bossrush'?'开始构筑':'选择军团',()=>start());updateHUD();};
start=function(){if(!R.active){oldStart();return;}if(R.mode==='bossrush'){draft(6,()=>encounter(),'首领连战 · 开局构筑');}else factionChoice();};
function choices(title,desc,options){S.status='upgrade';showOverlay(title,desc,'',()=>{});$('start').style.display='none';const wrap=document.createElement('div');wrap.id='upgradeOptions';wrap.className='choice-list';const token=++R.choiceToken;options.forEach(o=>{const b=document.createElement('button');b.className='upgrade '+(o.family?'family-'+o.family:'');const strong=document.createElement('strong');strong.textContent=o.title;const small=document.createElement('small');small.textContent=o.text;b.append(strong,small);b.onclick=()=>{if(token!==R.choiceToken)return;R.choiceToken++;wrap.querySelectorAll('button').forEach(x=>x.disabled=true);o.action();};wrap.appendChild(b);});$('overlayText').after(wrap);}
function factionChoice(){choices('选择你的军团','实心弹无限；特殊弹限量，击破补给箱和敌方模块可补充。',[{title:'✹ 爆破队',text:'浓缩火药 I · 所有炮弹伤害 +25%',action:()=>{R.cards.powder=1;encounter();}},{title:'⟁ 蜂群队',text:'分裂棱镜 I · 倍率门额外生成 3 弹',action:()=>{R.cards.prism=1;encounter();}},{title:'◆ 穿甲队',text:'钨钢弹芯 I · 穿甲伤害 +40%',action:()=>{R.cards.tungsten=1;encounter();}}]);}
function draft(count,next,title='选择升级'){const pool=CARDS.filter(c=>level(c.id)<c.max).sort(()=>Math.random()-.5).slice(0,3);const opts=pool.map(c=>({title:c.icon+' '+c.name+' '+(level(c.id)+1)+'/'+c.max,text:c.family+' · '+c.text,family:c.family,action:()=>{R.cards[c.id]=level(c.id)+1;if(c.id==='engineer')repair(S.player,6);count>1?draft(count-1,next,title):next();}}));if(alive(S.player)<S.player.length)opts.push({title:'紧急修复 30 块',text:'放弃本次升级，立即修补受损城墙',action:()=>{repair(S.player,30);count>1?draft(count-1,next,title):next();}});if(!opts.length)opts.push({title:'满构筑补给',text:'修复城堡，获得本场伤害 +20%',action:()=>{repair(S.player,30);R.tempDamage=(R.tempDamage||0)+.2;count>1?draft(count-1,next,title):next();}});choices(title+(count>1?' · 还可选 '+count+' 次':''),'升级保留到本局结束。',opts);}
function routeChoice(next){const opts=[{title:'安全营地',text:'立即修复 18 块，下一战按常规强度',action:()=>{repair(S.player,18);next();}},{title:'精英军械库',text:'下一战敌军更强，获胜额外选一张卡',action:()=>{R.nextElite=true;next();}}];const available=CARDS.filter(c=>level(c.id)>0&&level(c.id)<c.max);if(available.length)opts.push({title:'旧日实验室',text:'随机升级一张已有卡；下一战无法使用护盾',action:()=>{const c=available[Math.floor(Math.random()*available.length)];R.cards[c.id]++;if(c.id==='engineer')repair(S.player,6);R.noGuard=true;toast(c.name+' 升级');next();}});choices('前方岔路','选择收益，也承担清楚可见的代价。',opts);}
function saveRun(){const record=R.cleared;if(record>R.record){R.record=record;try{localStorage.setItem('siege-best-'+R.mode,String(record));}catch{}}saveBest();}
function victory(){if(R.resolved)return;R.resolved=true;R.tempDamage=0;R.cleared=R.stage;saveRun();if(R.stage>=MODES[R.mode].total){S.status='ended';showOverlay(R.mode==='survival'?'突围成功！':'远征胜利！','攻破 '+R.cleared+' 城 · '+Object.values(R.cards).reduce((a,b)=>a+b,0)+' 次升级 · '+S.score+' 分','再来一局',()=>reset(R.mode));return;}repair(S.player,(R.mode==='bossrush'?25:6)+6*level('engineer'));const cleared=R.stage,count=(R.mode==='bossrush'?2:1)+R.extraReward;draft(count,()=>{const next=()=>{R.stage++;encounter();};if(R.mode==='expedition'&&[1,4,7].includes(cleared))routeChoice(next);else next();},'第 '+cleared+' 城已攻破');}
finish=function(win){if(!R.active){oldFinish(win);return;}if(win){victory();return;}if(R.resolved)return;R.resolved=true;saveRun();S.status='ended';showOverlay(R.mode==='survival'&&S.time>=420?'突围时间已到':'防线被突破了','已攻破 '+R.cleared+' 城 · 本模式最佳 '+R.record+' 城。试着先打断敌方武器，再选择火力路线。','重新出征',()=>reset(R.mode));};
upgrade=function(){if(R.active)victory();else oldUpgrade();};
function freshIntent(){const e=R.enemy;let pattern=e.pattern;if(R.phase2&&e.boss)pattern=['charge',e.id==='titan'?'doubleHeavy':'meteor'];let value=pattern[R.enemyTurn%pattern.length];if(R.disabled&&(e.id==='raider'||e.id==='artillery'))value='single';return value;}
function inspectModules(){for(const m of R.modules){if(!m.disabled&&m.cells.filter(b=>!b.alive).length>=2){m.disabled=true;R.disabled=true;if(R.enemy.id==='raider'&&R.intent==='double')R.intent='single';if(['artillery','titan','eclipse'].includes(R.enemy.id))R.skip=true;if(['armor','titan'].includes(R.enemy.id))S.enemy.forEach(b=>b.armor=0);if(R.enemy.id==='eclipse'&&R.modules.every(m=>m.disabled))R.barrier=0;toast(m.name+' 已毁！');}}if(R.enemy.boss&&!R.phase2&&alive(S.enemy)/S.enemy.length<=.5){R.phase2=true;toast(R.enemy.name+' 进入过载阶段');}}
function guard(){if(!R.active||S.status!=='playing'||S.phase!=='aim'||R.guardUsed)return;R.guardUsed=true;R.guardHits=4+2*level('guard');toast('护盾展开 · 拦截 '+R.guardHits+' 弹');updateHUD();}
function projectileStats(p){p.damage=(1+.25*level('powder')+(R.tempDamage||0))*(p.ammo==='pierce'?1+.4*level('tungsten'):1);p.radius=p.ammo==='heavy'?62+12*level('blast'):p.ammo==='pierce'?18:31;p.maxHits=4+2*level('drill');p.baseGateTier=0;p.volleyId=R.volley;return p;}
fire=function(side='player'){if(!R.active)return oldFire(side);if(R.resolved||!alive(S.player)||alive(S.enemy)<=Math.ceil(S.enemy.length*.15))return false;if(side==='enemy'){inspectModules();if(R.skip){R.skip=false;R.enemyTurn++;R.intent=freshIntent();R.volleySide='enemy';S.shotOwner='enemy';S.phase='aftermath';S.phaseTime=0;S.focusX=1370;toast('动力模块损毁 · 敌方停火');return true;}if(R.enemy.id==='workshop'&&!R.disabled&&R.enemyRepairs<3){repair(S.enemy,5);R.enemyRepairs++;}if(R.intent==='charge'){R.enemyTurn++;R.intent=freshIntent();R.volleySide='enemy';S.shotOwner='enemy';S.phase='aftermath';S.phaseTime=0;S.focusX=1370;toast('敌方正在蓄力！下一炮准备反制');return true;}}
const ok=oldFire(side);if(!ok)return false;R.volley++;R.volleySide=side;R.enemySpawned=side==='enemy'?1:0;R.echoUsed=0;R.salvageCount=0;R.salvageRepaired=0;const core=S.bullets[S.bullets.length-1];if(side==='player')projectileStats(core);else{const intent=R.intent,n=intent==='double'||intent==='doubleHeavy'?2:intent==='meteor'?3:1;core.ammo=['heavy','doubleHeavy','meteor'].includes(intent)?'heavy':'normal';core.damage=core.ammo==='heavy'?1.25:1;core.radius=core.ammo==='heavy'?52:27;core.maxHits=1;for(let i=1;i<n;i++){const angle=Math.atan2(core.vy,core.vx)+(i-(n-1)/2)*.045,speed=Math.hypot(core.vx,core.vy);const p=projectile(core.x,core.y,Math.cos(angle)*speed,Math.sin(angle)*speed,'enemy',core.ammo);Object.assign(p,{damage:core.damage,radius:core.radius,maxHits:1,volleyId:R.volley});S.bullets.push(p);R.enemySpawned++;}R.enemyTurn++;R.intent=freshIntent();}updateHUD();return true;};
split=function(p,g){if(!R.active)return oldSplit(p,g);p.passed=true;p.baseGateTier=g.mult;const desired=p.side==='player'?g.mult+3*level('prism'):Math.min(g.mult,1+Math.max(0,R.budget-R.enemySpawned));if(p.side==='player'&&g.mult>=10)p.damage*=1+.2*level('overload');const spread=p.side==='player'?Math.pow(.7,level('focus')):1;for(let i=1;i<desired;i++){const q=projectile(p.x+(p.side==='player'?1:-1)*rand(1,6),p.y+rand(-8,8)*spread,p.vx*(1+rand(-.045,.04)*spread),p.vy+rand(-50,50)*spread,p.side,p.ammo,desired);Object.assign(q,{passed:true,damage:p.damage,radius:p.radius,maxHits:p.maxHits,baseGateTier:g.mult,volleyId:p.volleyId});S.bullets.push(q);if(p.side==='enemy')R.enemySpawned++;}p.mult=desired;if(p.side==='player')S.maxMult=Math.max(S.maxMult,desired);S.labels.push({x:g.x,y:p.y,text:(p.side==='enemy'?'敌军 ':'')+'×'+desired,life:1.1,color:g.color});S.rings.push({x:p.x,y:p.y,r:18,life:.4,max:.4,color:g.color});beep(520,.12);};
breakBlock=function(b,p){if(!R.active){oldBreak(b,p);return;}if(!b.alive)return;let damage=damageValue(p,b);if(p.side==='player'&&b.armor>0&&p.ammo!=='pierce'){const absorbed=Math.min(b.armor,damage);b.armor-=absorbed;damage-=absorbed;}b.hp-=damage;if(b.hp>0)return;b.alive=false;S.terrainRevision++;explode(b.x+b.w/2,b.y+b.h/2,b.terrain?'#527f85':b.side==='enemy'?'#e8d6b8':'#d8e5df',4);if(p.side==='player'){if(!b.terrain)S.destroyed++;S.score+=b.terrain?2:10*S.wave;}};
impact=function(b,p){if(!R.active)return oldImpact(b,p);if(p.side==='enemy'&&!b.terrain&&R.guardHits>0){R.guardHits--;p.ttl=0;S.rings.push({x:p.x,y:p.y,r:14,life:.4,max:.4,color:'#89e9ff'});return;}if(p.side==='player'&&!b.terrain&&R.barrier>0){R.barrier--;p.ttl=0;S.rings.push({x:p.x,y:p.y,r:18,life:.5,max:.5,color:'#d5a0ff'});return;}p.hits++;const list=b.terrain?S.terrain:(p.side==='player'?S.enemy:S.player),radius=p.radius||31;const hit=list.filter(q=>q.alive&&!p.hitIds.has(q)&&Math.hypot(q.x+q.w/2-p.x,q.y+q.h/2-p.y)<radius);if(!hit.includes(b)&&!p.hitIds.has(b))hit.push(b);for(const q of hit){p.hitIds.add(q);breakBlock(q,p);}explode(p.x,p.y,'#ffce7a',p.ammo==='heavy'?14:7);S.focusX=p.x;
if(p.side==='player'&&p.ammo==='heavy'&&!b.terrain&&level('echo')&&R.echoUsed<6){R.echoUsed++;R.aftershocks.push({x:p.x,y:p.y,delay:.3,damage:(p.damage||1)*.4,volleyId:p.volleyId});}if(p.ammo==='pierce'){if(b.terrain&&p.side==='player'&&level('drill'))p.hits--;if(p.hits>=(p.maxHits||4))p.ttl=0;else p.vx*=p.side==='player'&&level('drill')?.94:.86;}else p.ttl=0;};
cameraStep=function(dt){if(!R.active){oldCamera(dt);return;}S.phaseTime+=dt;if(S.phase==='flight'){const active=S.bullets.filter(p=>p.side===S.shotOwner).sort((a,b)=>a.x-b.x);if(active.length)S.focusX=active[Math.floor(active.length/2)].x+(S.shotOwner==='player'?Math.min(100,viewW*.14):0);else if(!R.aftershocks.length){inspectModules();S.phase='aftermath';S.phaseTime=0;if(R.volleySide==='enemy'){R.guardHits=0;if(R.enemy.id==='eclipse'&&R.modules.some(m=>!m.disabled))R.barrier=3;}}}else if(S.phase==='aftermath'&&S.phaseTime>2.4&&(!S.chunks.some(c=>!c.settled)||S.phaseTime>4.5)){S.phase='return';S.phaseTime=0;}else if(S.phase==='return'){S.focusX=220;if(S.phaseTime>1.3&&!R.resolved){S.phase='aim';S.phaseTime=0;S.nextOwner='player';if(R.volleySide==='player'){fire('enemy');}else{R.volleySide=null;S.shotOwner=null;}}}let target=clamp(S.focusX-viewW*.46,0,Math.max(0,WORLD.w-viewW));if(S.phase==='aim')target=0;S.camera+=(target-S.camera)*(1-Math.exp(-dt*(S.phase==='return'?3:5)));};
step=function(dt){if(!R.active){oldStep(dt);return;}if(S.status==='playing'){const before=S.destroyed;for(const shock of R.aftershocks)shock.delay-=dt;for(const shock of R.aftershocks.filter(e=>e.delay<=0)){explode(shock.x,shock.y,'#ffd57a',9);for(const b of S.enemy){if(b.alive&&Math.hypot(b.x+b.w/2-shock.x,b.y+b.h/2-shock.y)<36)breakBlock(b,{side:'player',ammo:'heavy',damage:shock.damage});}}R.aftershocks=R.aftershocks.filter(e=>e.delay>0);oldStep(dt);const gained=S.destroyed-before;if(gained&&level('salvage')){R.salvageCount+=gained;const allowance=Math.min(5*level('salvage'),Math.floor(R.salvageCount/10)*level('salvage'));if(allowance>R.salvageRepaired){repair(S.player,allowance-R.salvageRepaired);R.salvageRepaired=allowance;}}inspectModules();if(!R.resolved&&alive(S.enemy)<=Math.ceil(S.enemy.length*.15)){for(const b of S.enemy)if(b.alive){b.hp=0;breakBlock(b,{side:'player',ammo:'normal',damage:100,noLoot:true});}S.nextOwner='player';}if(S.status==='playing'&&R.mode==='survival'&&S.time>=420)finish(false);}else oldStep(dt);};
updateHUD=function(){oldHUD();$('arena').classList.toggle('shot-active',S.phase!=='aim');if(!R.active)return;$('modeLabel').textContent=MODES[R.mode].name;$('levelTitle').textContent='已攻破 '+R.cleared+' 城 · 最佳 '+R.record;$('waveBadge').textContent=(R.enemy?.boss?'BOSS ':R.elite?'ELITE ':'STAGE ')+String(R.stage).padStart(2,'0');$('clockLabel').textContent=R.mode==='survival'?'限时 07:00':'本局';$('enemyName').textContent=R.enemy?.name||'等待出征';$('enemyTrait').textContent=R.enemy?.boss?'首领':R.elite?'精英':'常规';$('intentText').textContent=R.skip?'武器损毁 · 下一轮停火':'下一轮：'+(INTENTS[R.intent]||'实心炮击');$('enemyStage').textContent=R.enemy?(R.enemy.trait+(R.barrier?' · 屏障 '+R.barrier+' 层':'')):'';$('buildCount').textContent=Object.values(R.cards).reduce((a,b)=>a+b,0);$('runProgress').textContent='第 '+R.stage+(Number.isFinite(MODES[R.mode].total)?' / '+MODES[R.mode].total:'')+' 战';$('shieldButton').disabled=R.guardUsed||S.phase!=='aim'||S.status!=='playing';$('shieldButton').textContent=R.guardHits?'护盾 '+R.guardHits+' 层':R.guardUsed?'护盾已用':'护盾 ×1';};
block=function(b){oldBlock(b);if(!R.active||b.side!=='enemy')return;if(b.armor>0){ctx.fillStyle='#667c8d77';ctx.fillRect(b.x,b.y,b.w,b.h);ctx.strokeStyle='#dce8ec';ctx.lineWidth=1.5;ctx.strokeRect(b.x+2,b.y+2,b.w-4,b.h-4);}if(b.module){const mod=R.modules[b.module-1];if(mod&&!mod.disabled){ctx.fillStyle=R.enemy.color+'88';ctx.fillRect(b.x+2,b.y+2,b.w-4,b.h-4);ctx.strokeStyle=R.enemy.color;ctx.lineWidth=2;ctx.strokeRect(b.x+1,b.y+1,b.w-2,b.h-2);}}};
drawCastle=function(side){if(side!=='enemy'||!R.active||!R.enemy){oldCastleDraw(side);if(side==='player'&&R.active&&R.guardHits){ctx.strokeStyle='#8ce9ff';ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(180,610,132,188,0,Math.PI,2*Math.PI);ctx.stroke();}return;}const base=1250,width=R.enemy.cols*23;ctx.fillStyle='#273e45';ctx.beginPath();ctx.roundRect(base-15,751,width+30,36,18);ctx.fill();ctx.fillStyle='#ec963f';ctx.fillRect(base-5,748,width+10,18);for(let i=0;i<R.enemy.cols;i++){ctx.strokeStyle='#b7a078';ctx.lineWidth=3;ctx.fillStyle='#243c45';ctx.beginPath();ctx.arc(base+10+i*23,775,10,0,Math.PI*2);ctx.fill();ctx.stroke();}for(const b of S.enemy.filter(b=>b.alive).sort((a,b)=>a.y-b.y||b.x-a.x))block(b);if(R.barrier){ctx.strokeStyle='#d9b4ff';ctx.lineWidth=5;ctx.globalAlpha=.7;ctx.beginPath();ctx.ellipse(base+width/2,580,width*.7,220,0,Math.PI,2*Math.PI);ctx.stroke();ctx.globalAlpha=1;}const p=source('enemy');ctx.save();ctx.translate(p.x,p.y);ctx.rotate(Math.PI+.55);ctx.fillStyle=R.enemy.boss?'#655070':'#3d5360';ctx.fillRect(-20,-12,53,24);ctx.fillStyle='#263c45';ctx.fillRect(27,-15,12,30);ctx.restore();};
drawGates=function(){oldGatesDraw();if(R.active&&level('prism'))for(const g of S.gates){ctx.fillStyle='#ffe7a4';ctx.font='bold 16px Arial';ctx.textAlign='center';ctx.fillText('+'+3*level('prism')+' 弹',g.x,g.y+g.h/2+36);}};
$('shieldButton').onclick=guard;$('buildButton').onclick=()=>{if(S.status==='playing')pause();const list=$('buildList');list.replaceChildren();for(const c of CARDS.filter(c=>level(c.id))){const p=document.createElement('p');p.className='owned-card';p.textContent=c.icon+' '+c.name+' '+level(c.id)+'/'+c.max+' · '+c.text;list.appendChild(p);}if(!list.children.length)list.textContent='尚未获得升级。';$('buildDialog').showModal();};$('closeBuild').onclick=()=>$('buildDialog').close();
window.siege.rogue={state:()=>({mode:R.mode,active:R.active,stage:R.stage,cards:{...R.cards},enemy:R.enemy?.id,intent:R.intent,guard:R.guardHits,enemySpawned:R.enemySpawned,budget:R.budget,cleared:R.cleared}),guard};
Object.assign(window.siege,{start,fire,pause,reset});
reset('expedition');
