'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const WORLD={w:1600,h:900,g:420};
const S={mode:'classic',ammo:'normal',status:'ready',angle:45,power:90,time:0,wave:1,score:0,destroyed:0,maxMult:1,shots:0,cooldown:0,enemyCooldown:6,player:[],enemy:[],terrain:[],bullets:[],particles:[],rings:[],labels:[],gates:[],camera:0,chunks:[],smoke:[],phase:'aim',phaseTime:0,focusX:200,shotOwner:null,nextOwner:'player',flash:0,terrainRevision:0,hudClock:0,previewCache:null,aimHit:null,shake:0,upgrades:{damage:1,reload:1,armor:1},toast:0,transition:0,best:0,sound:false};
try{S.best=Number(localStorage.getItem('siege-best')||0)}catch{}$('best').textContent=S.best;
let terrainCells=new Set();
let viewW=600,last=0,raf=0,audio=null,dragging=false,dragStart=null,accumulator=0;
const FIXED=1/120;
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);viewW=WORLD.h*r.width/r.height;}
new ResizeObserver(resize).observe(canvas);
function castle(side,wave=1){const blocks=[],base=side==='player'?90:1290,rows=side==='player'?11:11+Math.min(3,Math.floor(wave/3));for(let col=0;col<7;col++){let n=col===0||col===6?rows+2:rows;for(let row=0;row<n;row++){if(row===n-1&&col%2===1)continue;blocks.push({x:base+col*25,y:752-(row+1)*24,w:24,h:23,hp:side==='enemy'?1+Math.floor((wave-1)/3):1,alive:true,col,row,side,roof:(col===0||col===6)&&row===n-1});}}return blocks;}
function newTerrain(){let blocks=[];for(let x=430;x<=1150;x+=20){let h=Math.max(0,355*Math.exp(-(((x-575)/91)**2)),420*Math.exp(-(((x-1050)/83)**2)));for(let y=778;y>778-h;y-=20)blocks.push({x,y:y-20,w:20,h:20,hp:1,alive:true,terrain:true});}return blocks;}

function makeGates(){return[{x:795,y:160,h:164,mult:20,color:'#ffa52f'},{x:795,y:340,h:152,mult:10,color:'#31aff0'},{x:795,y:515,h:135,mult:5,color:'#6acc4a'}]}
function setup(){S.player=castle('player');S.enemy=castle('enemy',S.wave);S.terrain=newTerrain();S.gates=makeGates();S.bullets=[];S.particles=[];S.rings=[];S.labels=[];S.chunks=[];S.smoke=[];S.enemyCooldown=7;S.cooldown=0;S.transition=0;S.camera=0;S.phase='aim';S.phaseTime=0;S.focusX=200;S.shotOwner=null;S.nextOwner='player';S.flash=0;S.terrainRevision++;S.previewCache=null;S.hudClock=0;accumulator=0;updateHUD();}

function reset(mode=S.mode){S.mode=mode;S.status='ready';S.time=0;S.wave=1;S.score=0;S.destroyed=0;S.shots=0;S.maxMult=1;S.upgrades={damage:1,reload:1,armor:1};setup();document.querySelectorAll('.mode').forEach(e=>e.classList.toggle('active',e.dataset.mode===mode));$('modeLabel').textContent={classic:'经典炮战',survival:'七分钟守城 · 扩展模式',sandbox:'自由试炮场'}[mode];$('clockLabel').textContent=mode==='survival'?'守城目标 · 07:00':'战斗时间';showOverlay('爆裂城堡',mode==='survival'?'连续击退敌军，每波选择一项升级，坚持七分钟。':mode==='sandbox'?'城堡不会受到伤害。试试不同弹种、角度和倍率门。':'让炮弹穿过倍率门，摧毁对手的城堡。拖动战场或调整角度瞄准。','开始对战',()=>start());}
function start(){S.status='playing';$('overlay').classList.add('hidden');$('fire').disabled=false;$('pause').textContent='Ⅱ';toast(S.mode==='survival'?'七分钟守城 · 第 1 波':'瞄准倍率门，开火！');}
function showOverlay(title,text,button,action){$('overlay').classList.remove('hidden');$('overlayTitle').innerHTML=title;$('overlayText').textContent=text;const old=$('upgradeOptions');if(old)old.remove();$('start').style.display='flex';$('start').innerHTML=button+' <span>▶</span>';$('start').onclick=action;}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');S.toast=2.3;}
function beep(f=160,d=.12){if(!S.sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f/3,audio.currentTime+d);g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d);}catch{}}
function aim(v){S.angle=clamp(Number(v),10,65);$('angle').value=S.angle;$('angleValue').textContent=Math.round(S.angle);}
function source(side){const list=(side==='player'?S.player:S.enemy).filter(b=>b.alive);if(!list.length)return{x:side==='player'?260:1290,y:600};return{x:side==='player'?267:1288,y:Math.max(505,Math.min(...list.map(b=>b.y))+115)};}
function projectile(x,y,vx,vy,side,ammo='normal',mult=1){return{x,y,ox:x,oy:y,vx,vy,side,ammo,mult,passed:false,ttl:8,trail:[],hits:0,hitIds:new Set()};}
function fire(side='player'){if(S.status!=='playing'||S.phase!=='aim')return false;if(side==='player'&&(S.cooldown>0||S.nextOwner!=='player'))return false;const p=source(side);let a=S.angle*Math.PI/180,speed=770*S.power/100;if(side==='enemy'){const candidates=Array.from({length:23},(_,i)=>18+i*2);let best=-Infinity;for(const angle of candidates){const q=projectile(p.x,p.y,-Math.cos(angle*Math.PI/180)*710,-Math.sin(angle*Math.PI/180)*710,side);let target=null;for(let k=0;k<650&&q.ttl>0;k++){target=advanceBallistic(q,FIXED);if(target)break;}let value=target?.block?.side==='player'?100:target?.block?.terrain?10:0;value+=rand(0,6);if(value>best){best=value;a=angle*Math.PI/180;}}speed=710;}
const dir=side==='player'?1:-1;S.bullets.push(projectile(p.x,p.y,Math.cos(a)*speed*dir,-Math.sin(a)*speed,side,side==='player'?S.ammo:'normal'));S.phase='flight';S.phaseTime=0;S.shotOwner=side;S.focusX=p.x;
if(side==='player'){S.cooldown=(S.ammo==='heavy'?2.4:S.ammo==='pierce'?2:1.65)*S.upgrades.reload;S.shots++;}beep(170,.18);S.rings.push({x:p.x,y:p.y,r:8,life:.22,max:.22,color:'#ffeb9c'});return true;}

function explode(x,y,color='#ffc574',n=12){S.rings.push({x,y,r:5,life:.35,max:.35,color});for(let i=0;i<n;i++)S.particles.push({x,y,vx:rand(-160,160),vy:rand(-220,80),r:rand(2,7),life:rand(.4,1.5),color,rotation:rand(0,6)});S.shake=Math.min(6,S.shake+1.5);}
function breakBlock(b,bullet){if(!b.alive)return;b.hp-=(bullet.side==='player'?S.upgrades.damage:1);if(b.hp>0)return;b.alive=false;S.terrainRevision++;explode(b.x+12,b.y+12,b.terrain?'#527f85':b.side==='enemy'?'#e8d6b8':'#d8e5df',4);if(bullet.side==='player'){if(!b.terrain)S.destroyed++;S.score+=b.terrain?2:10*S.wave;}}
function impact(b,p){p.hits++;if(p.side==='enemy'&&S.mode==='sandbox'){p.ttl=0;return;}const radius=p.ammo==='heavy'?62:p.ammo==='pierce'?18:31,list=b.terrain?S.terrain:(p.side==='player'?S.enemy:S.player);explode(p.x,p.y,'#ffcf75',p.ammo==='heavy'?16:7);S.flash=Math.max(S.flash,.12);const hitBlocks=list.filter(q=>q.alive&&Math.hypot(q.x+q.w/2-p.x,q.y+q.h/2-p.y)<radius);if(!hitBlocks.includes(b))hitBlocks.push(b);for(const q of hitBlocks){if(p.hitIds.has(q))continue;p.hitIds.add(q);if(p.side==='enemy'&&S.upgrades.armor>1&&q.col%3===0)q.hp+=.25;breakBlock(q,p);}S.focusX=p.x;
if(p.ammo!=='pierce'||p.hits>=4)p.ttl=0;else p.vx*=.86;}

function split(p,gate){p.passed=true;p.mult=gate.mult;S.maxMult=Math.max(S.maxMult,gate.mult);S.labels.push({x:gate.x,y:p.y,text:'×'+gate.mult,life:1.2,color:gate.color});beep(500,.13);if(p.side==='player')toast('×'+gate.mult+' 倍弹幕！');const count=gate.mult;for(let i=1;i<count;i++){let q=projectile(p.x+rand(1,7),p.y+rand(-9,9),p.vx*rand(.93,1.04),p.vy+rand(-55,55),p.side,p.ammo,gate.mult);q.passed=true;S.bullets.push(q);}S.rings.push({x:p.x,y:p.y,r:15,life:.5,max:.5,color:gate.color});}
function collapse(blocks,side){const live=blocks.filter(b=>b.alive),byKey=new Map(live.map(b=>[b.col+','+b.row,b])),connected=new Set(),queue=live.filter(b=>b.row===0);for(const b of queue)connected.add(b);while(queue.length){const b=queue.shift();for(const [dc,dr] of [[1,0],[-1,0],[0,1],[0,-1]]){const n=byKey.get((b.col+dc)+','+(b.row+dr));if(n&&!connected.has(n)){connected.add(n);queue.push(n);}}}const loose=new Set(live.filter(b=>!connected.has(b)));while(loose.size){const first=loose.values().next().value,group=[first];loose.delete(first);for(let i=0;i<group.length;i++){const b=group[i];for(const [dc,dr] of [[1,0],[-1,0],[0,1],[0,-1]]){const n=byKey.get((b.col+dc)+','+(b.row+dr));if(n&&loose.has(n)){loose.delete(n);group.push(n);}}}const x=group.reduce((a,b)=>a+b.x+b.w/2,0)/group.length,y=group.reduce((a,b)=>a+b.y+b.h/2,0)/group.length;for(const b of group){b.alive=false;if(side==='player'){S.destroyed++;S.score+=10*S.wave;}}S.chunks.push({x,y,vx:side==='player'?35:-35,vy:-12,angle:0,spin:side==='player'?.42:-.42,life:6,settled:false,bounced:false,side,blocks:group.map(b=>({...b,x:b.x-x,y:b.y-y,alive:true}))});}}
function solidAt(p,x,y){const targets=p.side==='player'?S.enemy:S.player;return [...targets,...S.terrain].find(b=>b.alive&&!(b.crate&&p.side==='enemy')&&!p.hitIds.has(b)&&x>=b.x-3&&x<=b.x+b.w+3&&y>=b.y-3&&y<=b.y+b.h+3);}
function advanceBallistic(p,dt){p.ttl-=dt;p.ox=p.x;p.oy=p.y;const wind=typeof mapWind==='function'?mapWind():0;const nx=p.x+p.vx*dt+.5*wind*dt*dt,ny=p.y+p.vy*dt+.5*WORLD.g*dt*dt,parts=Math.max(1,Math.ceil(Math.hypot(nx-p.x,ny-p.y)/3));p.vy+=WORLD.g*dt;p.vx+=wind*dt;const ox=p.x,oy=p.y;for(let i=1;i<=parts;i++){p.x=ox+(nx-ox)*i/parts;p.y=oy+(ny-oy)*i/parts;const b=solidAt(p,p.x,p.y);if(b)return{block:b,x:p.x,y:p.y};if(p.y>784||p.x<0||p.x>WORLD.w)return{world:true,x:p.x,y:p.y};}return null;}
function previewShot(){const origin=source('player'),a=S.angle*Math.PI/180,v=770*S.power/100,p=projectile(origin.x,origin.y,Math.cos(a)*v,-Math.sin(a)*v,'player'),points=[{x:p.x,y:p.y}];let gate=null,hit=null;for(let i=0;i<900;i++){hit=advanceBallistic(p,FIXED);if(!gate&&p.ox<795&&p.x>=795)gate=S.gates.find(g=>p.y>=g.y&&p.y<=g.y+g.h)||null;if(i%8===0||hit)points.push({x:p.x,y:p.y});if(hit||p.ttl<=0)break;}return{points,hit,gate};}
function stepChunks(dt){for(const c of S.chunks){c.life-=dt;if(c.settled)continue;c.vy+=WORLD.g*dt;c.x+=c.vx*dt;c.y+=c.vy*dt;c.angle+=c.spin*dt;const cos=Math.cos(c.angle),sin=Math.sin(c.angle);let penetration=0;for(const b of c.blocks){for(const [lx,ly] of [[b.x,b.y+b.h],[b.x+b.w,b.y+b.h]]){const x=c.x+lx*cos-ly*sin,y=c.y+lx*sin+ly*cos;let ground=784;const solids=[...S.terrain,...(c.side==='player'?S.enemy:S.player)];for(const q of solids){if(q.alive&&x>=q.x&&x<=q.x+q.w&&y>=q.y&&y<=q.y+q.h+Math.max(10,c.vy*dt+5))ground=Math.min(ground,q.y);}penetration=Math.max(penetration,y-ground);}}if(penetration>0&&c.vy>0){c.y-=penetration;if(!c.bounced){c.vy=-Math.min(100,c.vy*.18);c.vx*=.3;c.spin*=.45;c.bounced=true;explode(c.x,c.y,'#ddceb1',Math.min(18,c.blocks.length));beep(90,.16);}else{c.vy=0;c.vx=0;c.spin=0;c.settled=true;}}}S.chunks=S.chunks.filter(c=>c.life>0);}
function cameraStep(dt){S.phaseTime+=dt;if(S.phase==='flight'){const active=S.bullets.filter(p=>p.side===S.shotOwner).sort((a,b)=>a.x-b.x);if(active.length){S.focusX=active[Math.floor(active.length/2)].x;if(S.shotOwner==='player')S.focusX+=Math.min(110,viewW*.14);}else{S.phase='aftermath';S.phaseTime=0;}}else if(S.phase==='aftermath'&&S.phaseTime>2.4&&(!S.chunks.some(c=>!c.settled)||S.phaseTime>4.5)){S.phase='return';S.phaseTime=0;}else if(S.phase==='return'){S.focusX=220;if(S.phaseTime>1.3){S.phase='aim';S.phaseTime=0;S.shotOwner=null;if(S.nextOwner==='enemy'&&S.mode!=='sandbox'){S.nextOwner='player';fire('enemy');}else S.nextOwner='player';}}let target=clamp(S.focusX-viewW*.46,0,Math.max(0,WORLD.w-viewW));if(S.phase==='aim')target=0;S.camera+=(target-S.camera)*(1-Math.exp(-dt*(S.phase==='return'?3:5)));}

function step(dt){if(S.toast>0){S.toast-=dt;if(S.toast<=0)$('toast').classList.remove('visible');}if(S.status!=='playing')return;S.time+=dt;S.cooldown=Math.max(0,S.cooldown-dt);S.flash=Math.max(0,S.flash-dt);if(S.mode==='survival'&&S.time>=420){finish(false);return;}if(S.mode==='survival')for(let i=0;i<S.gates.length;i++)S.gates[i].y=[160,340,515][i]+Math.sin(S.time*.45+i)*15;
for(const p of [...S.bullets]){if(p.ttl<=0)continue;const hit=advanceBallistic(p,dt);if(!p.passed&&((p.side==='player'&&p.ox<795&&p.x>=795)||(p.side==='enemy'&&p.ox>795&&p.x<=795))){const gate=S.gates.find(g=>p.y>=g.y&&p.y<=g.y+g.h);if(gate)split(p,gate);else p.passed=true;}if(hit?.block)impact(hit.block,p);else if(hit?.world){if(p.y>784)explode(p.x,786,'#b6f2f3',5);p.ttl=0;}p.trail.push({x:p.x,y:p.y});if(p.trail.length>24)p.trail.shift();if(Math.random()<.45)S.smoke.push({x:p.x-8,y:p.y,vx:rand(-9,9),vy:rand(-12,3),life:1.1,r:rand(4,9)});}
collapse(S.enemy,'player');if(S.mode!=='sandbox')collapse(S.player,'enemy');S.bullets=S.bullets.filter(p=>p.ttl>0);stepChunks(dt);for(const p of S.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=320*dt;p.rotation+=dt*3;}S.particles=S.particles.filter(p=>p.life>0&&p.y<900);for(const p of S.smoke){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.r+=dt*12;}S.smoke=S.smoke.filter(p=>p.life>0).slice(-380);for(const r of S.rings){r.life-=dt;r.r+=dt*100;}S.rings=S.rings.filter(r=>r.life>0);for(const l of S.labels){l.life-=dt;l.y-=dt*40;}S.labels=S.labels.filter(l=>l.life>0);S.shake*=Math.pow(.01,dt);
const oldPhase=S.phase;cameraStep(dt);if(oldPhase==='flight'&&S.phase==='aftermath')S.nextOwner=S.shotOwner==='player'&&S.mode!=='sandbox'?'enemy':'player';const playerAlive=S.player.some(b=>b.alive),enemyAlive=S.enemy.some(b=>b.alive);if(!playerAlive||!enemyAlive){S.transition+=dt;if(S.transition>3.6){if(!playerAlive)finish(false);else if(S.mode==='survival')upgrade();else if(S.mode==='sandbox'){S.wave++;S.enemy=castle('enemy',1);S.terrain=newTerrain();S.bullets=[];S.chunks=[];S.transition=0;S.phase='return';S.phaseTime=0;toast('靶场已重置');}else finish(true);}}S.hudClock+=dt;if(S.hudClock>=.1){S.hudClock=0;updateHUD();}}

function updateHUD(){$('angle').disabled=S.phase!=='aim';$('power').disabled=S.phase!=='aim';const p=Math.round(S.player.filter(b=>b.alive).length/Math.max(1,S.player.length)*100),e=Math.round(S.enemy.filter(b=>b.alive).length/Math.max(1,S.enemy.length)*100);$('playerHp').textContent=p+'%';$('enemyHp').textContent=e+'%';$('playerBar').style.width=p+'%';$('enemyBar').style.width=e+'%';$('timer').textContent=String(Math.floor(S.time/60)).padStart(2,'0')+':'+String(Math.floor(S.time%60)).padStart(2,'0');$('destroyed').innerHTML=S.destroyed+' <small>块</small>';$('score').textContent=S.score;$('maxMult').textContent='×'+S.maxMult;$('waveBadge').textContent=(S.mode==='survival'?'WAVE ':'ROUND ')+String(S.wave).padStart(2,'0');$('levelTitle').innerHTML=(S.mode==='survival'?'七分钟防线':S.mode==='sandbox'?'自由试炮场':'峡湾对决')+' <span>'+String(S.wave).padStart(2,'0')+'</span>';$('fire').disabled=S.status!=='playing'||S.cooldown>0||S.phase!=='aim'||S.nextOwner!=='player';$('fireStatus').textContent=S.status!=='playing'?'准备战斗':S.phase!=='aim'?({flight:'炮弹飞行中',aftermath:'观察战果',return:'镜头返回中'}[S.phase]||'准备中'):S.cooldown>0?'装填 '+S.cooldown.toFixed(1)+'s':'点击发射';$('shotStats').textContent=S.shots?'已发射 '+S.shots+' 次 · 最高倍率 ×'+S.maxMult:'命中倍率门，触发弹幕分裂';}
function saveBest(){if(S.score>S.best){S.best=S.score;try{localStorage.setItem('siege-best',String(S.best));}catch{}$('best').textContent=S.best;}}
function finish(win){S.status='ended';saveBest();updateHUD();showOverlay(win?(S.mode==='survival'?'守城成功！':'城堡已击破！'):'防线被突破了',win?(S.mode==='survival'?'你成功守住了七分钟！':'敌方城堡已被完全摧毁。')+' 本局积分 '+S.score+'，最大倍率 ×'+S.maxMult+'。':'试试更高倍率的弹道，或用爆破弹打开城墙。 本局积分 '+S.score+'。','再来一局',()=>{reset();start();});beep(win?700:110,.4);}
function upgrade(){S.status='upgrade';saveBest();showOverlay('第 '+S.wave+' 波已击退','选择一项升级，迎接下一轮攻势。','继续',()=>{});$('start').style.display='none';const wrap=document.createElement('div');wrap.id='upgradeOptions';const options=[['火力强化','炮弹伤害提升 35%',()=>S.upgrades.damage+=.35],['急速装填','装填时间减少 15%',()=>S.upgrades.reload*=.85],['紧急修复','修复城堡，并加强部分装甲',()=>{S.player=castle('player');S.upgrades.armor=2;}]];options.forEach(([name,desc,action])=>{const b=document.createElement('button');b.className='upgrade';b.textContent=name;const small=document.createElement('small');small.textContent=desc;b.appendChild(small);b.onclick=()=>{action();S.wave++;S.enemy=castle('enemy',S.wave);S.terrain=newTerrain();S.bullets=[];S.transition=0;S.enemyCooldown=5;S.status='playing';S.phase='return';S.phaseTime=0;S.nextOwner='player';S.shotOwner=null;S.chunks=[];wrap.remove();$('overlay').classList.add('hidden');toast('第 '+S.wave+' 波来袭');};wrap.appendChild(b);});$('overlayText').after(wrap);}
function pause(){if(S.status==='playing'){S.status='paused';$('pause').textContent='▶';showOverlay('暂时休整','战斗已暂停，准备好后继续。','继续战斗',()=>pause());}else if(S.status==='paused'){S.status='playing';$('pause').textContent='Ⅱ';$('overlay').classList.add('hidden');}updateHUD();}
function poly(points,fill){ctx.fillStyle=fill;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fill();}
function block(b){const x=b.x,y=b.y,w=b.w,h=b.h;if(b.terrain){ctx.fillStyle='#235460';ctx.fillRect(x,y,w+.4,h+.4);const top=!terrainCells.has(x+','+(y-20));if(top){ctx.fillStyle='#52868d';ctx.fillRect(x,y,w,4);ctx.fillStyle='#a0d3d4';ctx.fillRect(x+3,y,w-6,2);}ctx.fillStyle='#356b7425';ctx.fillRect(x,y,4,h);return;}const colors=b.side==='player'?['#eadfc5','#b4a993','#fff0cf']:['#efddbb','#bbab8b','#fff0c9'];ctx.fillStyle=colors[0];ctx.fillRect(x,y,w,h);poly([[x+w,y],[x+w+5,y-3],[x+w+5,y+h-3],[x+w,y+h]],colors[1]);poly([[x,y],[x+5,y-3],[x+w+5,y-3],[x+w,y]],colors[2]);ctx.strokeStyle='#8c785c30';ctx.lineWidth=.7;ctx.strokeRect(x,y,w,h);if((b.col===1||b.col===5)&&b.row%4===1){ctx.fillStyle='#48464a';ctx.beginPath();ctx.roundRect(x+5,y+3,14,19,[7,7,1,1]);ctx.fill();ctx.fillStyle='#faf0d9';ctx.beginPath();ctx.arc(x+12,y+10,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#383b43';ctx.fillRect(x+9,y+9,2,3);ctx.fillRect(x+13,y+9,2,3);ctx.fillStyle=b.side==='player'?'#57bceb':'#ef765b';ctx.fillRect(x+8,y+15,9,5);}if(b.roof){poly([[x-11,y],[x+12,y-43],[x+w+11,y]],b.side==='player'?'#398ac1':'#d95b4d');poly([[x+12,y-43],[x+w+11,y],[x+18,y]],b.side==='player'?'#296185':'#983d38');ctx.strokeStyle='#613c3540';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-11,y);ctx.lineTo(x+w+11,y);ctx.stroke();}}

function drawCastle(side){let bs=side==='player'?S.player:S.enemy,base=side==='player'?90:1290;ctx.fillStyle='#25434b';ctx.beginPath();ctx.ellipse(base+90,795,130,15,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#394648';ctx.beginPath();ctx.roundRect(base-18,752,218,37,18);ctx.fill();ctx.fillStyle='#ec963f';ctx.fillRect(base-8,750,195,20);for(let i=0;i<7;i++){ctx.fillStyle='#283b41';ctx.beginPath();ctx.arc(base+6+i*27,775,12,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#9b8b67';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#657574';ctx.beginPath();ctx.arc(base+6+i*27,775,4,0,Math.PI*2);ctx.fill();}for(const b of bs.filter(b=>b.alive).sort((a,b)=>a.y-b.y||b.x-a.x))block(b);const p=source(side);if(bs.some(b=>b.alive)){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(side==='player'?-S.angle*Math.PI/180:Math.PI+34*Math.PI/180);ctx.fillStyle='#253d47';ctx.fillRect(-22,-12,52,24);ctx.fillStyle='#6d8791';ctx.fillRect(-12,-11,43,6);ctx.fillStyle='#1d3038';ctx.fillRect(24,-15,13,30);ctx.restore();let peak=Math.min(...bs.filter(b=>b.alive).map(b=>b.y));ctx.strokeStyle='#654b38';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(base+85,peak-3);ctx.lineTo(base+85,peak-59);ctx.stroke();poly([[base+85,peak-59],[base+128,peak-48],[base+85,peak-31]],side==='player'?'#258ff0':'#ec6854');}}
function background(){terrainCells=new Set(S.terrain.filter(b=>b.alive).map(b=>b.x+','+b.y));let grad=ctx.createLinearGradient(0,0,0,900);grad.addColorStop(0,'#8ed8ef');grad.addColorStop(.65,'#cbebed');grad.addColorStop(1,'#4ba7b8');ctx.fillStyle=grad;ctx.fillRect(S.camera,0,viewW,900);ctx.fillStyle='#fff8';for(let i=0;i<7;i++){let x=i*285+30;ctx.beginPath();ctx.ellipse(x,150+(i%3)*62,65,14,0,0,7);ctx.ellipse(x+35,143+(i%3)*62,45,22,0,0,7);ctx.fill();}for(let layer=0;layer<3;layer++){let points=[[0,790]];for(let x=0;x<=1700;x+=65)points.push([x,590+layer*42-Math.abs(Math.sin(x*.009+layer*2))*125]);points.push([1700,790]);poly(points,['#a8ced4','#8bb8c3','#6c9eab'][layer]);}for(let x=45;x<1700;x+=180){const peak=495-Math.abs(Math.sin(x*.009))*95;poly([[x-45,peak+55],[x,peak],[x+38,peak+46],[x+14,peak+32],[x,peak+20],[x-15,peak+37]],'#e7f3ecaa');}ctx.fillStyle='#59b6c4';ctx.fillRect(0,784,1600,116);ctx.strokeStyle='#d3ffff99';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,786);ctx.lineTo(1600,786);ctx.stroke();ctx.strokeStyle='#a1e4e944';for(let i=0;i<25;i++){const x=(i*113+S.time*9)%1700;ctx.beginPath();ctx.moveTo(x,806+i%5*18);ctx.lineTo(x+randStable(i)*55+10,806+i%5*18);ctx.stroke();}for(let b of S.terrain.filter(b=>b.alive))block(b);}
function randStable(i){return(Math.sin(i*12.3)+1)/2;}
function drawGates(){for(const g of S.gates){ctx.save();ctx.shadowColor=g.color;ctx.shadowBlur=20;ctx.fillStyle=g.color+'88';ctx.fillRect(g.x-21,g.y,42,g.h);ctx.shadowBlur=0;ctx.strokeStyle=g.color;ctx.lineWidth=4;ctx.strokeRect(g.x-21,g.y,42,g.h);ctx.fillStyle='#fff';ctx.font='900 29px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.strokeStyle='#24465e';ctx.lineWidth=4;ctx.strokeText('×'+g.mult,g.x,g.y+g.h/2);ctx.fillText('×'+g.mult,g.x,g.y+g.h/2);ctx.strokeStyle=g.color+'55';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(g.x,g.y+g.h);ctx.lineTo(g.x,784);ctx.stroke();ctx.restore();}}
function trajectory(){if(S.phase!=='aim'||S.status==='ended'||S.status==='upgrade')return;const key=[S.angle,S.power,S.terrainRevision,S.player.filter(b=>b.alive).length,Math.round(S.gates[0].y),WORLD.g,typeof mapWind==='function'?mapWind():0].join(':');if(S.previewCache?.key!==key)S.previewCache={key,value:previewShot()};const preview=S.previewCache.value;S.aimHit=preview.hit;ctx.save();ctx.setLineDash([3,12]);ctx.lineWidth=2.5;ctx.strokeStyle='#fffdf0';ctx.beginPath();preview.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.setLineDash([]);if(preview.hit){const p=preview.hit;ctx.strokeStyle=p.block?.terrain?'#ffe68b':'#fffcdd';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,12,0,Math.PI*2);ctx.moveTo(p.x-18,p.y);ctx.lineTo(p.x+18,p.y);ctx.moveTo(p.x,p.y-18);ctx.lineTo(p.x,p.y+18);ctx.stroke();}ctx.restore();$('aimHint').textContent=preview.hit?.block?.terrain?'预计撞击山体 · 可炸开通路':preview.gate?'×'+preview.gate.mult+' 增殖 · 虚线为单发预估':'拖动调整角度与力度';}

function render(dt){resizeIfNeeded();const sx=canvas.width/viewW,sy=canvas.height/900;S.camera=clamp(S.camera,0,Math.max(0,1600-viewW));ctx.setTransform(sx,0,0,sy,-S.camera*sx,0);ctx.clearRect(S.camera,0,viewW,900);if(S.status==='playing'&&S.shake>0.1)ctx.translate(rand(-S.shake,S.shake),rand(-S.shake,S.shake));background();drawGates();drawCastle('player');drawCastle('enemy');for(const c of S.chunks){ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.angle);ctx.globalAlpha=Math.min(1,c.life);for(const b of c.blocks)block(b);ctx.restore();}trajectory();for(const p of S.smoke){ctx.globalAlpha=p.life*.25;ctx.fillStyle='#536477';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;for(const p of S.bullets){ctx.strokeStyle=p.side==='player'?'#ffffff99':'#ffb4a088';ctx.lineWidth=4;ctx.beginPath();p.trail.forEach((v,i)=>i?ctx.lineTo(v.x,v.y):ctx.moveTo(v.x,v.y));ctx.stroke();ctx.save();ctx.translate(p.x,p.y);ctx.rotate(Math.atan2(p.vy,p.vx));poly([[-12,-4],[8,-4],[15,0],[8,4],[-12,4]],p.ammo==='heavy'?'#ec9e3d':p.ammo==='pierce'?'#82e6fa':'#586c76');poly([[-12,-3],[-22,0],[-12,3]],'#ffc45d');ctx.restore();}for(const p of S.particles){ctx.globalAlpha=Math.min(1,p.life);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rotation);ctx.fillStyle=p.color;ctx.fillRect(-p.r/2,-p.r/2,p.r,p.r);ctx.restore();}ctx.globalAlpha=1;for(const r of S.rings){ctx.globalAlpha=r.life/r.max;ctx.strokeStyle=r.color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,Math.PI*2);ctx.stroke();}ctx.globalAlpha=1;for(const l of S.labels){ctx.globalAlpha=Math.min(1,l.life);ctx.fillStyle=l.color;ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.font='900 40px Arial';ctx.textAlign='center';ctx.strokeText(l.text,l.x,l.y);ctx.fillText(l.text,l.x,l.y);}ctx.globalAlpha=1;}
function resizeIfNeeded(){if(!canvas.width||!canvas.height)resize();}
function loop(t){const dt=Math.min((t-last)/1000||0,.1);last=t;accumulator+=dt;while(accumulator>=FIXED){step(FIXED);accumulator-=FIXED;}render(dt);raf=requestAnimationFrame(loop);}
$('power').addEventListener('input',e=>{S.power=Number(e.target.value);$('powerValue').textContent=S.power+'%';});
$('angle').addEventListener('input',e=>aim(e.target.value));$('fire').onclick=()=>fire();$('pause').onclick=pause;$('sound').onclick=()=>{S.sound=!S.sound;$('sound').textContent='音效：'+(S.sound?'开':'关');if(S.sound)beep(500,.12);};
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{if(S.mode===b.dataset.mode)return;reset(b.dataset.mode);$('settings').close();});document.querySelectorAll('.ammo').forEach(b=>b.onclick=()=>{S.ammo=b.dataset.ammo;document.querySelectorAll('.ammo').forEach(q=>q.classList.toggle('active',q===b));});
$('menu').onclick=()=>{if(S.status==='playing')pause();$('settings').showModal();};$('closeSettings').onclick=()=>$('settings').close();$('help').onclick=()=>{$('settings').close();if(S.status==='playing')pause();$('helpDialog').showModal();};$('closeHelp').onclick=$('helpDone').onclick=()=>$('helpDialog').close();
canvas.addEventListener('pointerdown',e=>{if(S.status!=='playing'||S.phase!=='aim')return;dragging=true;dragStart={x:e.clientX,y:e.clientY,angle:S.angle,power:S.power};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!dragging||!dragStart)return;const r=canvas.getBoundingClientRect();aim(dragStart.angle+(dragStart.y-e.clientY)/r.height*75);S.power=clamp(dragStart.power+(e.clientX-dragStart.x)/r.width*65,65,115);$('power').value=S.power;$('powerValue').textContent=Math.round(S.power)+'%';});canvas.addEventListener('pointerup',()=>{dragging=false;dragStart=null;});canvas.addEventListener('pointercancel',()=>{if(dragStart){aim(dragStart.angle);S.power=dragStart.power;$('power').value=S.power;$('powerValue').textContent=Math.round(S.power)+'%';}dragging=false;dragStart=null;});
window.addEventListener('keydown',e=>{if($('helpDialog').open||$('settings').open||$('buildDialog').open)return;if(e.target.tagName==='INPUT')return;if(['ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')aim(S.angle-1);if(e.key==='ArrowRight')aim(S.angle+1);if(e.code==='Space'){if(S.status==='ready')start();else if(S.status==='playing')fire();}if(e.key.toLowerCase()==='p')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&S.status==='playing')pause();});
window.siege={state:()=>({status:S.status,mode:S.mode,time:S.time,wave:S.wave,score:S.score,angle:S.angle,power:S.power,phase:S.phase,chunkCount:S.chunks.length,camera:S.camera,playerBlocks:S.player.filter(b=>b.alive).length,enemyBlocks:S.enemy.filter(b=>b.alive).length,bullets:S.bullets.length,maxMult:S.maxMult}),start,fire,pause,setAngle:aim,reset};
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_battle_state',description:'读取当前炮战状态、波次、角度和城堡剩余方块。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>window.siege.state()});document.modelContext.registerTool({name:'set_cannon_angle',description:'调整当前炮口仰角，不会开火。',inputSchema:{type:'object',properties:{angle:{type:'number',minimum:10,maximum:65}},required:['angle'],additionalProperties:false},execute:input=>{if(!input||typeof input.angle!=='number'||input.angle<10||input.angle>65)throw Error('角度必须在 10 至 65 度之间');aim(input.angle);return window.siege.state();}});}catch{}}
reset();aim(45);$('power').value=90;$('powerValue').textContent='90%';resize();raf=requestAnimationFrame(loop);
