'use strict';
// Tall structural challenge inspired by the second reference. Extra rules are independent extensions.
MODES.skyline={name:'摩天围城',total:5};
Object.assign(ENEMIES,{
spire:{name:'摩天守卫',tag:'楼层炮台',color:'#ffad69',hp:1.05,rows:29,cols:17,pattern:['double','charge','meteor'],tower:true,shape:'cactus',trait:'切断侧翼和中柱，摧毁三座独立炮台',moduleDrops:['cluster','pierce','arc']},
skybridge:{name:'双塔连城',tag:'楼层炮台',color:'#a8d9ff',hp:1.15,rows:28,cols:17,pattern:['double','charge','meteor'],tower:true,shape:'bridge',trait:'双柱承重；桥体坠落会带走上层炮台',moduleDrops:['pierce','frost','heavy']},
terrace:{name:'层叠要塞',tag:'楼层炮台',color:'#b6e5a3',hp:1.2,rows:27,cols:17,pattern:['single','double','heavy'],tower:true,shape:'terrace',trait:'逐层突破，寻找每层的连接支柱',moduleDrops:['acid','cluster','heavy']},
skyking:{name:'天际巨城',tag:'主炮台',color:'#dda5ff',hp:1.75,rows:29,cols:17,boss:true,pattern:['double','charge','meteor'],tower:true,shape:'cactus',trait:'巨型楼冠与三座重炮；切断承重比磨墙更有效',moduleDrops:['arc','frost','cluster']}
});
const T={scout:false,charge:0,armed:false,slots:['normal','heavy','pierce'],objective:false,delay:0};
const tReset=reset,tEncounter=encounter,tChoose=chooseEnemy,tBuild=buildEnemy,tFire=fire,tCamera=cameraStep,tStep=step,tHUD=updateHUD,tInspect=inspectModules,tIntent=freshIntent,tSource=source,tDraw=drawCastle,tBlock=block;
function towerMode(){return R.active&&R.mode==='skyline';}
function liveStations(){return R.modules.filter(m=>!m.disabled);}
function towerCell(shape,c,r){if(shape==='bridge'){if(r<3)return(c>=2&&c<=5)||(c>=11&&c<=14);if(r<23){const pier=((c>=3&&c<=5)||(c>=12&&c<=14))&&!([4,13].includes(c)&&r%4<2);return pier||([15,16].includes(r)&&c>=3&&c<=14);}return c>=1&&c<=16&&!(r===25&&c%3===0);}
if(shape==='terrace'){if(r<3)return c>=4&&c<=12;if(r<8)return c>=6&&c<=10&&!(c===8&&r%4<2);if(r<11)return c>=2&&c<=14;if(r<17)return((c>=3&&c<=5)||(c>=11&&c<=13))&&!([4,12].includes(c)&&r%4===1);if(r<20)return c>=1&&c<=15;if(r<23)return c>=6&&c<=10&&!(c===8&&r%3===0);return c>=3&&c<=13&&!(r===25&&c%3===0);}
if(r===0)return c>=4&&c<=13;if(r===1)return c>=5&&c<=12;if(r===2)return c>=6&&c<=11;if(r>=24)return c>=2&&c<=15&&!(r===26&&c%3===0);if(r>=21)return c>=6-(r-21)&&c<=11+(r-21);let core=c>=7&&c<=10&&!((c===8||c===9)&&r%4<2&&r>3);let left=(r>=10&&r<=14&&c>=Math.max(0,15-r)&&c<=7)||(r>=15&&r<=16&&c>=1&&c<=3);let right=(r>=8&&r<=12&&c>=10&&c<=r+4)||(r>=13&&r<=14&&c>=14&&c<=16);return core||left||right;}
chooseEnemy=function(){if(towerMode())return ['spire','skybridge','terrace','spire','skyking'][Math.min(4,R.stage-1)];return tChoose();};
buildEnemy=function(id,elite=false){if(!ENEMIES[id]?.tower){tBuild(id,elite);return;}const e=ENEMIES[id];R.enemy={...e,id};R.elite=elite||R.stage===4;R.budget=e.boss?8:R.elite?6:4;R.enemyTurn=0;R.enemyRepairs=0;R.phase2=false;R.disabled=false;R.skip=false;R.barrier=0;const blocks=[],base=1190,w=20,h=20,hp=e.hp*(1+.1*(R.stage-1))*(R.elite?1.15:1);for(let r=0;r<e.rows;r++)for(let c=0;c<17;c++)if(towerCell(e.shape,c,r))blocks.push({x:base+c*w,y:752-(r+1)*h,w:19,h:19,col:c,row:r,side:'enemy',hp,maxHp:hp,alive:true,armor:0});
const roofs=e.shape==='cactus'?[[2,29],[5,29],[8,29],[11,29],[14,29],[2,17],[15,15]]:e.shape==='bridge'?[[1,28],[5,28],[9,28],[13,28],[16,28]]:[[3,27],[6,27],[9,27],[12,27]];for(const [c,r] of roofs)blocks.push({x:base+c*w,y:752-(r+1)*h,w:19,h:19,col:c,row:r,side:'enemy',hp,maxHp:hp,alive:true,armor:0,roof:true});S.enemy=blocks;
let positions=e.shape==='cactus'?[[1,15],[14,13],[8,27]]:e.shape==='bridge'?[[3,20],[12,20],[8,26]]:[[3,17],[11,17],[7,25]];R.modules=positions.map(([c,r],index)=>{let cells=blocks.filter(b=>b.col>=c&&b.col<c+2&&b.row>=r&&b.row<r+2);if(cells.length<2)cells=blocks.filter(b=>Math.abs(b.col-c)+Math.abs(b.row-r)<=2).slice(0,4);cells.forEach(b=>b.module=index+1);return{id:index,name:['左翼炮台','右翼炮台','楼冠主炮'][index],cells,disabled:false};});R.intent='double';};
function stationPoint(m){const cells=m.cells.filter(b=>b.alive);if(!cells.length)return{x:1290,y:570};return{x:cells.reduce((a,b)=>a+b.x,0)/cells.length-12,y:cells.reduce((a,b)=>a+b.y,0)/cells.length+10};}
source=function(side){if(side==='enemy'&&R.active&&R.enemy?.tower&&liveStations().length)return stationPoint(liveStations()[0]);return tSource(side);};
function clampTowerIntent(value){const n=liveStations().length;if(value==='charge')return value;if(n<2)return'single';if(n<3&&value==='meteor')return'double';return value;}
freshIntent=function(){if(R.enemy?.tower)return clampTowerIntent(R.enemy.pattern[R.enemyTurn%R.enemy.pattern.length]);return tIntent();};
inspectModules=function(){tInspect();if(R.enemy?.tower){R.intent=clampTowerIntent(R.intent);if(!liveStations().length&&!T.objective){T.objective=true;T.delay=0;toast('三座炮台全部瘫痪！');}}};
reset=function(mode=S.mode){T.scout=false;T.charge=0;T.armed=false;T.objective=false;T.delay=0;tReset(mode);if(mode==='skyline'){$('overlayTitle').textContent='摩天围城';$('overlayText').textContent='切断巨型楼体的支撑，逐一摧毁侧翼与楼冠炮台。五场围攻，保留本局构筑和弹药。';}updateHUD();};
encounter=function(){T.scout=false;T.armed=false;T.objective=false;T.delay=0;tEncounter();if(towerMode()){T.charge=Math.max(T.charge,3);toast(R.enemy.name+' · 摧毁三座炮台或击垮楼体');}updateHUD();};
function salvoNeed(){const cost={};for(const a of T.slots)if(a!=='normal')cost[a]=(cost[a]||0)+1;return cost;}
function canSalvo(){return T.charge>=3&&Object.entries(salvoNeed()).every(([k,n])=>(V.inventory[k]||0)>=n);}
function salvoDialog(){if(S.status!=='playing'||S.phase!=='aim')return;pause();for(let i=0;i<3;i++){const el=$('salvo'+(i+1));el.replaceChildren();for(const [id,a] of Object.entries(AMMO)){const opt=document.createElement('option');opt.value=id;opt.textContent=a.name+' · '+(id==='normal'?'无限':V.inventory[id]+' 发');el.appendChild(opt);}el.value=T.slots[i];el.onchange=()=>{T.slots[i]=el.value;salvoCost();};}salvoCost();$('salvoDialog').showModal();}
function salvoCost(){const need=Object.entries(salvoNeed());$('salvoCost').textContent='火力 '+T.charge+'/3；消耗：'+(need.length?need.map(([k,n])=>AMMO[k].name+' ×'+n).join('、'):'仅实心弹')+(canSalvo()?'':'。火力或弹药不足。');$('armSalvo').disabled=!canSalvo();}
function aimFrom(point){let best={value:-Infinity,a:34*Math.PI/180};for(let deg=16;deg<=64;deg+=2){let a=deg*Math.PI/180,q=projectile(point.x,point.y,-Math.cos(a)*710,-Math.sin(a)*710,'enemy'),hit;for(let k=0;k<700&&q.ttl>0;k++){hit=advanceBallistic(q,FIXED);if(hit)break;}const score=hit?.block?.side==='player'?100:hit?.block?.terrain?2:0;if(score>best.value)best={value:score,a};}return best.a;}
fire=function(side='player'){if(T.objective&&R.enemy?.tower)return false;if(side==='player'&&T.armed&&!canSalvo()){T.armed=false;toast('编组弹药不足，已取消齐射');return false;}const burst=side==='player'&&T.armed,previousAmmo=S.ammo;if(burst)S.ammo=T.slots[0];const before=S.bullets.length,ok=tFire(side);if(!ok){S.ammo=previousAmmo;return false;}const made=S.bullets.slice(before);if(side==='player'&&made.length){T.scout=false;if(burst){const core=made[0],a=Math.atan2(core.vy,core.vx),speed=Math.hypot(core.vx,core.vy);for(let i=1;i<3;i++){const type=T.slots[i],angle=a+(i===1?-.035:.035);const p=projectile(core.x,core.y,Math.cos(angle)*speed,Math.sin(angle)*speed,'player',type);if(R.active)projectileStats(p);specialStats(p);S.bullets.push(p);if(type!=='normal'){V.inventory[type]--;V.spent++;}}T.charge=0;T.armed=false;toast('混合齐射！');if(S.ammo!=='normal'&&V.inventory[S.ammo]===0)S.ammo='normal';}else T.charge=Math.min(3,T.charge+1);}
if(side==='enemy'&&made.length&&R.enemy?.tower){const stations=liveStations();made.forEach((p,i)=>{const m=stations[i%stations.length];if(!m){p.ttl=0;return;}const pos=stationPoint(m),a=aimFrom(pos);Object.assign(p,{x:pos.x,y:pos.y,ox:pos.x,oy:pos.y,vx:-Math.cos(a)*710,vy:-Math.sin(a)*710,ammo:i%2?'heavy':'normal',damage:i%2?1.15:1,radius:i%2?44:27,trail:[]});});}syncAmmo();updateHUD();return ok;};
cameraStep=function(dt){if(T.scout&&S.phase==='aim'&&S.status==='playing'){S.phaseTime+=dt;const target=Math.max(0,WORLD.w-viewW);S.camera+=(target-S.camera)*(1-Math.exp(-dt*5));return;}tCamera(dt);};
step=function(dt){const active=S.status==='playing';tStep(dt);if(active&&T.objective&&R.enemy?.tower&&!R.resolved&&S.status==='playing'){T.delay+=dt;if(T.delay>3.4&&!S.bullets.some(p=>p.side==='player'))victory();}};
updateHUD=function(){tHUD();if(T.objective&&R.enemy?.tower)$('fire').disabled=true;$('salvoMeter').textContent=T.armed?'已装填':T.charge+'/3';$('salvoButton').disabled=S.status!=='playing'||S.phase!=='aim';$('scoutButton').disabled=S.status!=='playing'||S.phase!=='aim';$('scoutButton').textContent=T.scout?'返回炮台':'侦察敌堡';$('stationCounter').textContent=R.enemy?.tower?'炮台 '+liveStations().length+'/3':'';$('arena').classList.toggle('tower-view',!!R.enemy?.tower&&(T.scout||S.phase!=='aim'));if(R.enemy?.tower){$('enemyStage').textContent='楼体 '+Math.round(alive(S.enemy)/S.enemy.length*100)+'% · 武器站 '+liveStations().length+'/3';$('intentText').textContent=T.objective?'敌方炮台已全部瘫痪':V.frozen?'冻结：下一行动暂停':'下一轮：'+(R.intent==='charge'?'楼层重炮蓄力':(R.intent==='meteor'?3:R.intent==='double'?2:1)+' 座炮台混合射击');}};
block=function(b){tBlock(R.enemy?.tower&&b.side==='enemy'?{...b,col:-1}:b);};
drawCastle=function(side){if(side!=='enemy'||!R.enemy?.tower){tDraw(side);return;}const base=1190;ctx.fillStyle='#273d45';ctx.beginPath();ctx.roundRect(base+78,751,204,37,18);ctx.fill();ctx.fillStyle='#dc964d';ctx.fillRect(base+82,747,194,20);for(let i=0;i<7;i++){ctx.fillStyle='#2d3e46';ctx.strokeStyle='#d5b98c';ctx.lineWidth=3;ctx.beginPath();ctx.arc(base+93+i*26,775,11,0,Math.PI*2);ctx.fill();ctx.stroke();}for(const b of S.enemy.filter(b=>b.alive).sort((a,b)=>a.y-b.y||b.x-a.x))block(b);for(const m of liveStations()){const p=stationPoint(m);ctx.save();ctx.translate(p.x+8,p.y);ctx.fillStyle=['#db8c57','#82b6cc','#b59acb'][m.id];ctx.fillRect(-7,-10,16,20);ctx.fillStyle='#f1e7d2';ctx.beginPath();ctx.arc(1,-14,7,0,7);ctx.fill();ctx.fillStyle='#343844';ctx.fillRect(-3,-16,3,3);ctx.fillRect(3,-16,3,3);ctx.fillStyle='#263e4b';ctx.fillRect(-27,0,30,9);ctx.restore();}};
$('scoutButton').onclick=()=>{if(S.status==='playing'&&S.phase==='aim')T.scout=!T.scout;updateHUD();};$('salvoButton').onclick=salvoDialog;$('closeSalvo').onclick=()=>{$('salvoDialog').close();if(S.status==='paused')pause();};$('cancelSalvo').onclick=()=>{T.armed=false;$('salvoDialog').close();if(S.status==='paused')pause();};$('armSalvo').onclick=()=>{if(!canSalvo())return;T.armed=true;$('salvoDialog').close();if(S.status==='paused')pause();toast('齐射已装填，点击开火');updateHUD();};
Object.assign(window.siege,{start,fire,pause,reset});window.siege.tower={state:()=>({mode:R.mode,stations:R.enemy?.tower?liveStations().length:null,charge:T.charge,armed:T.armed,scout:T.scout,objective:T.objective})};
reset('skyline');
