(()=>{'use strict';
const $=id=>document.getElementById(id),E=HexWar,canvas=$('board'),ctx=canvas.getContext('2d'),W=480,H=625,S=44,R=S/Math.sqrt(3),OX=40,OY=44;
const icons={castle:'♜',mine:'◆',barracks:'⚔',archer:'➶',tower:'♜',knight:'♞',mystery:'?'};
let difficulty='normal',state=E.create(5400,difficulty),selected=null,speed=1,last=0,uiTimer=0,sound=false,audio=null,toastTimer=0,wasPlaying=false,renderTime=0,particles=[];
function point(c){return {x:OX+c.x*S,y:OY+c.y*S};}
function resize(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw();}
function poly(x,y,r){ctx.beginPath();for(let i=0;i<6;i++){const a=(60*i-90)*Math.PI/180;const px=x+Math.cos(a)*r,py=y+Math.sin(a)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py);}ctx.closePath();}
function roundRect(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function line(x1,y1,x2,y2,color,width=1){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
function ellipse(x,y,rx,ry,fill){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();}
function label(text,x,y,size,color,weight='700'){ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${weight} ${size}px system-ui,sans-serif`;ctx.fillStyle=color;ctx.fillText(text,x,y);}
function building(c,preview=false){const p=point(c),b=c.building;if(!b)return;const friendly=b.side===0,col=friendly?'#72a0b5':'#bf5c51',light=friendly?'#9bc1c6':'#f09572';ctx.save();ctx.translate(p.x,p.y-3);ellipse(0,11,17,7,'#25432240');
 // Fortified stone base.
 poly(0,3,R*.84);ctx.fillStyle='#667866';ctx.fill();ctx.lineWidth=4;ctx.strokeStyle='#d2d3b0';ctx.stroke();ctx.lineWidth=1;ctx.strokeStyle='#f2e9c8';ctx.stroke();
 const t=b.type;
 if(t==='mine'){roundRect(-14,-6,28,18,3,'#795832');ellipse(0,5,12,7,'#61472c');for(const [x,y,z]of [[-7,1,8],[3,2,10],[1,-6,8]]){ctx.beginPath();ctx.moveTo(x-z/2,y+z/2);ctx.lineTo(x-z/3,y-z/2);ctx.lineTo(x+z/3,y-z/2-2);ctx.lineTo(x+z/2,y+z/2);ctx.closePath();ctx.fillStyle='#f1c443';ctx.fill();line(x-z/3,y-z/2,x+z/3,y-z/2-2,'#fff09b',2);}line(-13,13,13,13,'#ac853d',3);}
 else if(t==='barracks'||t==='archer'){roundRect(-12,-9,24,24,2,'#d9cca2');roundRect(-4,4,8,11,2,'#3d5450');ctx.beginPath();ctx.moveTo(-16,-8);ctx.lineTo(0,-21);ctx.lineTo(16,-8);ctx.closePath();ctx.fillStyle=col;ctx.fill();line(-16,-8,0,-21,light,2);line(0,-21,16,-8,'#33545b',2);if(t==='archer'){ctx.beginPath();ctx.arc(0,-5,7,-1.2,1.2);ctx.strokeStyle='#efe3a8';ctx.lineWidth=2;ctx.stroke();line(3,-11,3,1,'#f5e7bd');}else{line(-5,-14,5,-5,'#e1e6d7',2);line(5,-14,-5,-5,'#e1e6d7',2);}}
 else {const tall=t==='castle'?31:t==='tower'?35:27;roundRect(-11,-tall+7,22,tall+8,2,'#b1bba6');roundRect(-11,-tall+7,6,tall+8,1,'#d9d8b9');roundRect(-5,3,10,12,3,'#425f55');for(const x of [-12,-3,6])roundRect(x,-tall,6,11,1,'#d8d7bb');line(-12,-tall+12,12,-tall+12,'#6a7f70',2);roundRect(-3,-tall+14,6,7,1,col);if(t==='castle'||t==='knight'){line(0,-tall-2,0,-tall-15,'#ebdfb0',2);ctx.beginPath();ctx.moveTo(1,-tall-15);ctx.lineTo(14,-tall-11);ctx.lineTo(1,-tall-6);ctx.fillStyle=friendly?'#daed78':'#f48266';ctx.fill();}if(t==='knight')label('♞',0,-13,16,'#34555a');}
 if(UNITTYPE(t)){const ratio=b.timer/E.TYPES[t].period;ctx.beginPath();ctx.arc(13,15,5,-Math.PI/2,-Math.PI/2+ratio*Math.PI*2);ctx.strokeStyle=friendly?'#ecf794':'#ffb789';ctx.lineWidth=3;ctx.stroke();}
 if(b.hp<b.maxHp&&!preview){roundRect(-16,-43,32,4,2,'#1b3435');roundRect(-15,-42,30*Math.max(0,b.hp/b.maxHp),2,1,friendly?'#e4f386':'#ffa78d');}
 ctx.restore();}
function UNITTYPE(t){return !!E.UNIT[t];}
function troop(u){const x=OX+u.x*S,y=OY+u.y*S,ours=u.side===0,large=u.type==='knight',k=large?1.2:1;ctx.save();ctx.translate(x+(u.id%3-1)*3,y+Math.sin(u.walk*12)*.8);ctx.scale(k,k);ellipse(0,5,5.5,2.4,'#153e3b50');line(-2,2,-3,6,'#334852',2);line(2,2,3,6,'#334852',2);roundRect(-4,-4,8,8,2,ours?'#e6d991':'#d77460');ellipse(0,-6,4.5,4.5,'#ccc9af');roundRect(-4,-8,8,3,1,ours?'#527f95':'#973c3a');line(0,-12,0,-9,ours?'#e6ee90':'#f1b19a',2);if(u.type==='archer'){ctx.beginPath();ctx.arc(5,0,5,-1.3,1.3);ctx.lineWidth=1.5;ctx.strokeStyle='#826c3c';ctx.stroke();line(6,-5,6,5,'#efdeb3');}else{line(6,3,6,-10,'#eeeece',1.5);line(3,-4,8,-4,'#657979',2);ellipse(-4,0,3,4,ours?'#789fbc':'#c25648');}if(u.attack>0){ellipse(0,-2,7,7,'#fff0bb66');}if(u.hp<u.maxHp){roundRect(-7,-17,14,3,1,'#214844');roundRect(-7,-17,14*Math.max(0,u.hp/u.maxHp),3,1,ours?'#dce986':'#f7957d');}ctx.restore();}
function draw(){renderTime=performance.now()/1000;ctx.clearRect(0,0,W,H);const sea=ctx.createLinearGradient(0,0,W,H);sea.addColorStop(0,'#63afbd');sea.addColorStop(1,'#307993');ctx.fillStyle=sea;ctx.fillRect(0,0,W,H);
 for(let i=0;i<35;i++){const x=(i*83)%W,y=(i*131)%H;line(x+Math.sin(renderTime*.4+i)*3,y,x+12+Math.sin(renderTime*.4+i)*3,y,'#cef3ee17',2);}
 const choices=E.available(state,0),choiceSet=new Set(choices.map(c=>c.id));
 for(const c of state.cells){if(c.water)continue;const p=point(c);poly(p.x,p.y+4,R-.3);ctx.fillStyle=c.owner===0?'#73863d':'#a84f41';ctx.fill();poly(p.x,p.y,R-.5);const grad=ctx.createLinearGradient(p.x,p.y-R,p.x,p.y+R);if(c.owner===0){grad.addColorStop(0,c.flash?'#ebf6a4':'#cada76');grad.addColorStop(1,'#adc45c');}else{grad.addColorStop(0,c.flash?'#ffd7a5':'#e28369');grad.addColorStop(1,'#ca6956');}ctx.fillStyle=grad;ctx.fill();ctx.strokeStyle=c.owner===0?'#edf4ad55':'#ffc0a544';ctx.lineWidth=1;ctx.stroke();
 if(!c.building&&!choiceSet.has(c.id)&&((c.id*13)%17===0)){line(p.x-3,p.y+4,p.x-5,p.y,c.owner===0?'#7d9e4760':'#b5544860');line(p.x-2,p.y+4,p.x+1,p.y-2,c.owner===0?'#7d9e4760':'#b5544860');}
 if(choiceSet.has(c.id)&&(state.phase!=='ready'||c.r>=11)){ctx.save();poly(p.x,p.y,R-4);ctx.strokeStyle=c.id===selected?'#fffde5':'#f8f3ca90';ctx.lineWidth=c.id===selected?2.8:1.3;ctx.setLineDash(c.id===selected?[]:[3,3]);ctx.stroke();ctx.restore();label(icons[c.offer],p.x,p.y-5,16,'#41583b');label('◆ '+E.TYPES[c.offer].cost,p.x,p.y+10,8,state.gold[0]>=E.TYPES[c.offer].cost?'#526436':'#8f7750');}
 }
 for(const c of state.cells)if(c.building)building(c);
 state.units.slice().sort((a,b)=>a.y-b.y).forEach(troop);
 if(selected!==null){const c=state.cells[selected],p=point(c);ctx.save();poly(p.x,p.y,R+1);ctx.lineWidth=2;ctx.strokeStyle='#fff8ce';ctx.shadowColor='#fff1b4';ctx.shadowBlur=9;ctx.stroke();ctx.restore();}
 for(const p of particles){const t=(performance.now()-p.birth)/650;if(t>=1)continue;ctx.globalAlpha=1-t;label(p.text,p.x,p.y-t*22,12,p.color);ctx.globalAlpha=1;}
 particles=particles.filter(p=>performance.now()-p.birth<650);
}
function toast(text){$('toast').textContent=text;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),2600);}
function beep(freq=600,length=.08){if(!sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+length);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+length);}catch{sound=false;}}
function updateUI(){const a=E.stats(state,0),b=E.stats(state,1);$('gold').textContent=a.gold;$('income').textContent=`+${a.income} / 秒`;$('units').textContent=a.units;$('ourLand').textContent=a.land;$('enemyLand').textContent=b.land;$('landMeter').style.width=`${100*a.land/(a.land+b.land)}%`;
 const time=Math.max(0,Math.ceil(E.DURATION-state.elapsed));$('clock').textContent=`${String(Math.floor(time/60)).padStart(2,'0')}:${String(time%60).padStart(2,'0')}`;$('phaseLabel').textContent=state.phase==='ready'?'准备出征':state.phase==='paused'?'战场暂停':state.phase==='over'?'战斗结束':'领土争夺中';
 $('pause').disabled=!['playing','paused'].includes(state.phase);$('speed').disabled=state.phase==='over';
 const c=selected!==null?state.cells[selected]:null,buildable=c&&E.available(state,0).some(t=>t.id===c.id),type=c&&(c.building?.type||c.offer);
 if(c){$('selectionIcon').textContent=c.water?'≈':icons[type];$('selectionTitle').textContent=c.water?'湖泊 · 无法通行':c.building?`${c.building.side===0?'我方':'敌方'}${E.TYPES[type].name}`:`${E.TYPES[type].name} · 第 ${c.r+1} 排`;$('selectionDescription').textContent=c.water?'部队会自动选择两侧陆路。':c.building?`${E.TYPES[type].description} 耐久 ${Math.ceil(c.building.hp)}/${c.building.maxHp}`:buildable?E.TYPES[type].description:c.owner===1?'这是敌方领地，需要派出军队占领。':'要先建造相邻地块，与主城保持连接。';$('build').textContent=c.building?'已建造':c.water?'湖泊':`建造\n◆ ${E.TYPES[type].cost}`;$('build').disabled=!buildable||state.phase!=='playing'||state.gold[0]<E.TYPES[type].cost;}
 else{$('selectionIcon').textContent='⌖';$('selectionTitle').textContent='点击发光的相邻地块';$('selectionDescription').textContent='金矿赚钱，兵营自动出兵。军队会占领经过的敌方地格。';$('build').textContent='选择\n地块';$('build').disabled=true;}
 const choices=state.phase==='playing'?E.available(state,0):[];const key=choices.map(c=>`${c.id}:${c.id===selected}`).join('|');if($('quickBuilds').dataset.key!==key){$('quickBuilds').dataset.key=key;$('quickBuilds').replaceChildren(...choices.map(c=>{const b=document.createElement('button');b.textContent=`${icons[c.offer]} ${E.TYPES[c.offer].name} ${E.TYPES[c.offer].cost}`;b.setAttribute('aria-label',`选择第 ${c.r+1} 排第 ${c.c+1} 列的${E.TYPES[c.offer].name}`);b.classList.toggle('selected',c.id===selected);b.addEventListener('click',()=>select(c.id));return b;}));}
 const hasMine=state.cells.some(c=>c.building?.side===0&&c.building.type==='mine'),hasArmy=state.cells.some(c=>c.building?.side===0&&UNITTYPE(c.building.type));$('hint').textContent=!hasMine?'先建金矿，持续获得金币':!hasArmy?'建设兵营，部队会自动出征':time<30?'最后冲刺！时间到比较领地数量':'沿湖岸自动推进 · 继续扩建支援前线';
 if(state.phase==='over'&&$('result').classList.contains('hidden'))showResult();
}
function select(id){selected=id;updateUI();draw();}
function buy(){if(selected===null)return;const c=state.cells[selected],result=E.purchase(state,selected);if(!result.ok){toast(result.reason);return;}const p=point(c);particles.push({x:p.x,y:p.y-20,text:`−${result.cost}`,color:'#fff4a1',birth:performance.now()});beep(result.type==='knight'?880:520,.12);toast(c.offer==='mystery'?`盲盒揭晓：${E.TYPES[result.type].name}！`:`${E.TYPES[result.type].name}建造完成`);updateUI();draw();}
function start(fresh=true){if(fresh)state=E.create(Math.floor(Math.random()*0x7fffffff),difficulty);state.phase='playing';selected=null;particles=[];$('opening').classList.add('hidden');$('result').classList.add('hidden');$('pauseOverlay').classList.add('hidden');$('pause').textContent='Ⅱ';$('pause').setAttribute('aria-label','暂停游戏');last=performance.now();updateUI();beep(440,.1);}
function pause(){if(state.phase==='playing'){state.phase='paused';$('pauseOverlay').classList.remove('hidden');$('pause').textContent='▷';$('pause').setAttribute('aria-label','继续游戏');}else if(state.phase==='paused'){state.phase='playing';$('pauseOverlay').classList.add('hidden');$('pause').textContent='Ⅱ';$('pause').setAttribute('aria-label','暂停游戏');last=performance.now();}updateUI();}
function showResult(){const win=state.winner===0,draw=state.winner===null;$('resultIcon').textContent=draw?'⚑':win?'♛':'♜';$('resultKicker').textContent=draw?'DRAW':win?'VICTORY':'TRY AGAIN';$('resultTitle').textContent=draw?'势均力敌！':win?'王国属于你！':'下一次，夺回来。';$('resultReason').textContent=state.reason;$('resultLand').textContent=E.stats(state,0).land;$('resultBuilds').textContent=state.builds[0];$('resultKills').textContent=state.kills[0];$('result').classList.remove('hidden');$('again').focus();beep(win?784:240,.25);}
function openDialog(id){wasPlaying=state.phase==='playing';if(wasPlaying)pause();$(id).showModal();}
canvas.addEventListener('pointerdown',e=>{if(state.phase!=='playing')return;const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*W,y=(e.clientY-rect.top)/rect.height*H;let nearest=null,dist=Infinity;for(const c of state.cells){const p=point(c),d=Math.hypot(x-p.x,y-p.y);if(d<dist){dist=d;nearest=c;}}if(nearest&&dist<=R)select(nearest.id);});
canvas.addEventListener('keydown',e=>{if(state.phase!=='playing')return;let c=state.cells[selected??112];if(e.key==='Enter'){e.preventDefault();if(selected===null)select(111);else buy();return;}const offsets={ArrowLeft:-1,ArrowRight:1,ArrowUp:-E.COLS,ArrowDown:E.COLS};if(e.key in offsets){e.preventDefault();select(Math.max(0,Math.min(state.cells.length-1,c.id+offsets[e.key])));}});
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!document.querySelector('dialog[open]')&&e.target.tagName!=='BUTTON'){e.preventDefault();pause();}});
$('start').onclick=()=>start();$('build').onclick=buy;$('pause').onclick=pause;$('resume').onclick=pause;$('restartPause').onclick=()=>start();$('again').onclick=()=>start();$('menu').onclick=()=>{state=E.create(5400,difficulty);selected=null;$('result').classList.add('hidden');$('opening').classList.remove('hidden');updateUI();};$('speed').onclick=()=>{speed=speed===1?2:1;$('speed').textContent=speed+'×';};$('sound').onclick=()=>{sound=!sound;$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'关闭音效':'开启音效');$('sound').style.color=sound?'#e3ee9c':'';if(sound)beep();toast(sound?'音效已开启':'音效已关闭');};$('help').onclick=()=>openDialog('helpDialog');$('provenance').onclick=()=>openDialog('sourceDialog');document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('close',()=>{if(wasPlaying&&state.phase==='paused')pause();wasPlaying=false;}));document.querySelectorAll('[data-difficulty]').forEach(b=>b.onclick=()=>{difficulty=b.dataset.difficulty;document.querySelectorAll('[data-difficulty]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.phase==='playing')pause();});window.addEventListener('resize',resize);
function frame(now){const delta=last?Math.min((now-last)/1000,.25):0;last=now;if(state.phase==='playing'){let left=delta*speed;while(left>.0001){const dt=Math.min(left,.05);E.tick(state,dt);left-=dt;}uiTimer+=delta;if(uiTimer>.12){updateUI();uiTimer=0;}}if(state.phase==='over'&&$('result').classList.contains('hidden'))updateUI();draw();requestAnimationFrame(frame);}resize();updateUI();requestAnimationFrame(frame);
})();
