(()=>{'use strict';
const $=id=>document.getElementById(id),E=HexWar,canvas=$('board'),ctx=canvas.getContext('2d'),W=480,H=625,S=44,R=S/Math.sqrt(3),OX=40,OY=44;
const shortDescriptions={castle:'守住主城，失守即败。',mine:'每秒 +3 金，持续供给。',barracks:'每 7 秒出兵，自动占地。',archer:'每 9 秒出弓手，远程攻击。',tower:'攻击附近敌军，稳住防线。',knight:'每 13 秒出重骑，强力推进。',arsenal:'手动轰击 / 穿透炮，独立储弹。',hospital:'治疗附近友军，支持前线。',beacon:'附近训练 +20%、攻击 +10%。',mystery:'随机揭晓一种建筑。'};
const icons={castle:'♜',mine:'◆',barracks:'⚔',archer:'➶',tower:'♜',knight:'♞',arsenal:'◎',hospital:'✚',beacon:'⚑',mystery:'?'};
let difficulty='normal',mode='trio',map='lake',seed=5400,state=E.create(seed,difficulty,{mode,map}),selected=null,speed=1,last=0,uiTimer=0,sound=false,audio=null,toastTimer=0,wasPlaying=false,renderTime=0,particles=[],weaponEffects=[],selectedBuildType=null,aim=null,activePanel='manage',decision=null,gesture=null,zoomed=false;
const neutral={name:'中立领地',label:'中',color:'#a5b3a3',light:'#c4d0ba',dark:'#667b70'};
function faction(id){return id<0?neutral:E.FACTIONS[id]||neutral;}
function shortName(id){return id<0?'中立':faction(id).name.slice(0,2);}
function palette(id){return id===0?{color:'#dec26a',light:'#f4dfa0',dark:'#93804a'}:faction(id);}
function point(c){return {x:OX+c.x*S,y:OY+c.y*S};}
function layoutBoard(){const view=$('boardViewport'),width=view.clientWidth,height=view.clientHeight;if(!width||!height)return;const w=zoomed?Math.max(width,380):Math.min(width,height*W/H);canvas.style.width=w+'px';canvas.style.height=w*H/W+'px';}
function resize(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);layoutBoard();draw();}
function resetGesture(){gesture=null;$('battlefield').classList.remove('is-dragging');}
function compactScreen(){return window.innerWidth<780&&window.innerHeight<=690;}
function setTray(open){$('commandPanel').classList.toggle('tray-collapsed',!open);$('toggleTray').setAttribute('aria-expanded',String(open));$('toggleTray').setAttribute('aria-label',open?'收起操作详情':'展开建造类型与升级详情');$('toggleTray').textContent=open?'收起⌄':'更多⌃';layoutBoard();}
function setZoom(on){resetGesture();zoomed=on;$('battlefield').classList.toggle('is-zoomed',on);$('zoom').setAttribute('aria-pressed',String(on));$('zoom').setAttribute('aria-label',on?'显示完整地图':'放大地图，拖动查看地块');$('zoom').textContent=on?'⊖ 全图':'⊕ 放大';$('zoomNote').textContent=on?'拖动查看':'全图';layoutBoard();const view=$('boardViewport');if(on){const c=state.cells[selected??state.bases[0]],p=point(c),scale=parseFloat(canvas.style.width||W)/W;view.scrollLeft=Math.max(0,p.x*scale-view.clientWidth/2);view.scrollTop=Math.max(0,p.y*scale-view.clientHeight/2);}else{view.scrollLeft=0;view.scrollTop=0;}}

function poly(x,y,r){ctx.beginPath();for(let i=0;i<6;i++){const a=(60*i-90)*Math.PI/180;const px=x+Math.cos(a)*r,py=y+Math.sin(a)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py);}ctx.closePath();}
function roundRect(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function line(x1,y1,x2,y2,color,width=1){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
function ellipse(x,y,rx,ry,fill){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();}
function label(text,x,y,size,color,weight='700'){ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${weight} ${size}px system-ui,sans-serif`;ctx.fillStyle=color;ctx.fillText(text,x,y);}
function building(c,preview=false){const p=point(c),b=c.building;if(!b)return;const friendly=b.side===0,colors=palette(b.side),col=colors.dark,light=colors.light;ctx.save();ctx.translate(p.x,p.y-3);ellipse(0,11,17,7,'#25432240');
 // Fortified stone base.
 poly(0,3,R*.84);ctx.fillStyle='#667866';ctx.fill();ctx.lineWidth=4;ctx.strokeStyle='#d2d3b0';ctx.stroke();ctx.lineWidth=1;ctx.strokeStyle='#f2e9c8';ctx.stroke();
 const t=b.type;
 if(t==='mine'){roundRect(-14,-6,28,18,3,'#795832');ellipse(0,5,12,7,'#61472c');for(const [x,y,z]of [[-7,1,8],[3,2,10],[1,-6,8]]){ctx.beginPath();ctx.moveTo(x-z/2,y+z/2);ctx.lineTo(x-z/3,y-z/2);ctx.lineTo(x+z/3,y-z/2-2);ctx.lineTo(x+z/2,y+z/2);ctx.closePath();ctx.fillStyle='#f1c443';ctx.fill();line(x-z/3,y-z/2,x+z/3,y-z/2-2,'#fff09b',2);}line(-13,13,13,13,'#ac853d',3);}
 else if(t==='barracks'||t==='archer'){roundRect(-12,-9,24,24,2,'#d9cca2');roundRect(-4,4,8,11,2,'#3d5450');ctx.beginPath();ctx.moveTo(-16,-8);ctx.lineTo(0,-21);ctx.lineTo(16,-8);ctx.closePath();ctx.fillStyle=col;ctx.fill();line(-16,-8,0,-21,light,2);line(0,-21,16,-8,'#33545b',2);if(t==='archer'){ctx.beginPath();ctx.arc(0,-5,7,-1.2,1.2);ctx.strokeStyle='#efe3a8';ctx.lineWidth=2;ctx.stroke();line(3,-11,3,1,'#f5e7bd');}else{line(-5,-14,5,-5,'#e1e6d7',2);line(5,-14,-5,-5,'#e1e6d7',2);}}
 else if(t==='arsenal'){roundRect(-15,-8,30,21,3,'#666d64');roundRect(-12,-4,24,14,2,'#a2aaa0');ellipse(-9,12,5,5,'#354840');ellipse(9,12,5,5,'#354840');ellipse(-9,12,2,2,'#e1cd92');ellipse(9,12,2,2,'#e1cd92');ctx.save();ctx.rotate(-.5);roundRect(-6,-17,13,24,3,'#3c5350','#cbd6bb');roundRect(-7,-19,15,6,2,col,light);ctx.restore();roundRect(-11,0,7,5,1,'#e4c868');line(5,-7,13,-12,light,2);}
 else if(t==='hospital'){roundRect(-13,-11,26,25,3,'#e1dbc0');roundRect(-5,3,10,11,2,'#446b61');ctx.beginPath();ctx.moveTo(-17,-9);ctx.lineTo(0,-24);ctx.lineTo(17,-9);ctx.closePath();ctx.fillStyle='#518d79';ctx.fill();line(-17,-9,0,-24,'#b3e3bf',2);roundRect(-6,-13,12,12,2,'#f6f0d9');roundRect(-2,-11,4,8,1,'#c96350');roundRect(-4,-9,8,4,1,'#c96350');line(12,4,12,10,'#79af83',2);line(9,7,15,7,'#79af83',2);}
 else if(t==='beacon'){line(-10,12,-10,-27,'#dec797',3);ctx.beginPath();ctx.moveTo(-8,-27);ctx.lineTo(14,-21);ctx.lineTo(-8,-13);ctx.closePath();ctx.fillStyle=col;ctx.fill();line(-7,-26,10,-21,light,2);roundRect(-8,-3,24,17,3,'#af624b');ellipse(4,-3,12,5,'#eddbad');ellipse(4,12,12,4,'#7e503e');for(const x of [-5,3,11])line(x,0,x,11,'#e6ba78',1.5);line(-8,-9,8,-3,'#f5e2bc',2);line(14,-10,3,-2,'#f5e2bc',2);}
 else {const tall=t==='castle'?31:t==='tower'?35:27;roundRect(-11,-tall+7,22,tall+8,2,'#b1bba6');roundRect(-11,-tall+7,6,tall+8,1,'#d9d8b9');roundRect(-5,3,10,12,3,'#425f55');for(const x of [-12,-3,6])roundRect(x,-tall,6,11,1,'#d8d7bb');line(-12,-tall+12,12,-tall+12,'#6a7f70',2);roundRect(-3,-tall+14,6,7,1,col);if(t==='castle'||t==='knight'){line(0,-tall-2,0,-tall-15,'#ebdfb0',2);ctx.beginPath();ctx.moveTo(1,-tall-15);ctx.lineTo(14,-tall-11);ctx.lineTo(1,-tall-6);ctx.fillStyle=colors.color;ctx.fill();}if(t==='knight')label('♞',0,-13,16,'#34555a');}
 if(UNITTYPE(t)){const ratio=b.timer/E.TYPES[t].period;ctx.beginPath();ctx.arc(13,15,5,-Math.PI/2,-Math.PI/2+ratio*Math.PI*2);ctx.strokeStyle=colors.light;ctx.lineWidth=3;ctx.stroke();}
 if(t==='castle'){roundRect(-22,18,44,13,4,'#15332edf',colors.color+'99');label(shortName(b.side)+(b.side===0?'·你':'·AI'),0,25,8,colors.light);}
 if(t!=='castle'&&(b.level||1)>1){const branch=E.BUILDING_UPGRADES?.[t]?.[b.branch];roundRect(-22,18,44,12,4,'#1d3534ed',colors.light+'88');label(`${branch?branch.name.slice(0,2):'建筑'} ${b.level}级`,0,24,8,colors.light);}
 if(t==='arsenal'){for(let i=0;i<Math.min(b.ammo||0,5);i++)roundRect(-11+i*5,-30,3,7,1,'#f6d574');}
 if(b.hp<b.maxHp&&!preview){roundRect(-16,-43,32,4,2,'#1b3435');roundRect(-15,-42,30*Math.max(0,b.hp/b.maxHp),2,1,colors.light);}
 ctx.restore();}
function UNITTYPE(t){return !!E.UNIT[t];}
function troop(u){const x=OX+u.x*S,y=OY+u.y*S,ours=u.side===0,colors=palette(u.side),large=u.type==='knight',k=large?1.2:1;ctx.save();ctx.translate(x+(u.id%3-1)*3,y+Math.sin(u.walk*12)*.8);ctx.scale(k,k);ellipse(0,5,5.5,2.4,'#153e3b50');line(-2,2,-3,6,'#334852',2);line(2,2,3,6,'#334852',2);roundRect(-4,-4,8,8,2,colors.color);ellipse(0,-6,4.5,4.5,'#ccc9af');roundRect(-4,-8,8,3,1,colors.dark);line(0,-12,0,-9,colors.light,2);if(u.type==='archer'){ctx.beginPath();ctx.arc(5,0,5,-1.3,1.3);ctx.lineWidth=1.5;ctx.strokeStyle='#826c3c';ctx.stroke();line(6,-5,6,5,'#efdeb3');}else{line(6,3,6,-10,'#eeeece',1.5);line(3,-4,8,-4,'#657979',2);ellipse(-4,0,3,4,colors.dark);}if(u.attack>0){ellipse(0,-2,7,7,'#fff0bb66');}if(u.hp<u.maxHp){roundRect(-7,-17,14,3,1,'#214844');roundRect(-7,-17,14*Math.max(0,u.hp/u.maxHp),3,1,colors.light);}ctx.restore();}
function outpost(c){const p=point(c),colors=palette(c.owner),gold=c.outpost==='gold';ctx.save();ctx.translate(p.x,p.y);ellipse(0,8,15,6,'#173d3440');poly(0,1,15);ctx.fillStyle='#d6d1ad';ctx.fill();ctx.lineWidth=2;ctx.strokeStyle=colors.dark;ctx.stroke();if(gold){roundRect(-9,-5,18,12,2,'#6d725a');label('◆',0,-1,19,'#f4d470');}else{line(-4,8,-4,-17,'#e6e7c9',2);ctx.beginPath();ctx.moveTo(-3,-16);ctx.lineTo(13,-11);ctx.lineTo(-3,-5);ctx.fillStyle=colors.dark;ctx.fill();label('⚑',3,-9,11,colors.light);}roundRect(-18,13,36,12,4,'#18362fdb');label(gold?'◆ 金哨':'⚑ 集结',0,19,8,gold?'#f1d898':'#d9e7ce');ctx.restore();}
function offerIcon(type,x,y){ctx.save();ctx.translate(x,y);const ink='#405331',light='#fff0be';if(type==='mine'){ctx.beginPath();ctx.moveTo(0,-8);ctx.lineTo(8,0);ctx.lineTo(0,8);ctx.lineTo(-8,0);ctx.closePath();ctx.fillStyle=ink;ctx.fill();line(-4,-1,0,-5,light,1.5);}else if(type==='barracks'){for(const d of [-1,1]){line(-6*d,-7,6*d,7,ink,3);line(0*d,5,5*d,0,ink,2);}line(-6,-7,-2,-5,light,1);}else if(type==='archer'){ctx.beginPath();ctx.arc(-4,0,9,-1.15,1.15);ctx.strokeStyle=ink;ctx.lineWidth=2.5;ctx.stroke();line(0,-8,0,8,ink,1);line(-6,0,10,0,ink,2);line(6,-3,10,0,ink,2);line(6,3,10,0,ink,2);}else if(type==='tower'||type==='knight'){roundRect(-7,-4,14,12,1,ink);for(const d of [-7,-1,5])roundRect(d,-9,3,7,0,ink);if(type==='knight'){line(0,-9,0,-14,ink,1.5);line(0,-14,6,-12,ink,2);}roundRect(-2,3,4,5,1,light);}else if(type==='arsenal'){ellipse(-6,5,3,3,ink);ellipse(6,5,3,3,ink);line(-4,1,8,-7,ink,6);line(-8,1,8,1,ink,4);}else if(type==='hospital'){roundRect(-3,-9,6,18,1,ink);roundRect(-9,-3,18,6,1,ink);}else if(type==='beacon'){line(-5,-10,-5,9,ink,2);ctx.beginPath();ctx.moveTo(-4,-10);ctx.lineTo(9,-6);ctx.lineTo(-4,-1);ctx.closePath();ctx.fillStyle=ink;ctx.fill();line(-9,9,0,9,ink,2);}else label('?',0,0,21,ink);ctx.restore();}
function drawFrontier(){for(const c of state.cells){if(!c.building)continue;const p=point(c);for(let edge=0;edge<6;edge++){const a=(edge*60-90)*Math.PI/180,b=((edge+1)*60-90)*Math.PI/180,m=(a+b)/2,neighbor=state.cells[c.neighbors.find(id=>{const q=point(state.cells[id]);return Math.hypot(q.x-(p.x+Math.cos(m)*S),q.y-(p.y+Math.sin(m)*S))<S*.22;})];if(neighbor?.building?.side===c.building.side)continue;const x1=p.x+Math.cos(a)*(R-1),y1=p.y+Math.sin(a)*(R-1),x2=p.x+Math.cos(b)*(R-1),y2=p.y+Math.sin(b)*(R-1);line(x1,y1+2,x2,y2+2,'#526b5c',4);line(x1,y1,x2,y2,'#ecead0',3);}}}
function draw(){renderTime=performance.now()/1000;ctx.clearRect(0,0,W,H);const sea=ctx.createLinearGradient(0,0,W,H);sea.addColorStop(0,'#63afbd');sea.addColorStop(1,'#307993');ctx.fillStyle=sea;ctx.fillRect(0,0,W,H);
 for(let i=0;i<35;i++){const x=(i*83)%W,y=(i*131)%H;line(x+Math.sin(renderTime*.4+i)*3,y,x+12+Math.sin(renderTime*.4+i)*3,y,'#cef3ee17',2);}
 const choices=E.available(state,0),choiceSet=new Set(choices.map(c=>c.id));
 for(const c of state.cells){if(c.water)continue;const p=point(c),colors=palette(c.owner);poly(p.x,p.y+4,R-.3);ctx.fillStyle=colors.dark;ctx.fill();poly(p.x,p.y,R-.5);const grad=ctx.createLinearGradient(p.x,p.y-R,p.x,p.y+R);grad.addColorStop(0,c.flash?'#fff4ca':colors.light);grad.addColorStop(1,colors.color);ctx.fillStyle=grad;ctx.fill();ctx.strokeStyle=colors.light+'55';ctx.lineWidth=1;ctx.stroke();
 if(!c.building&&!c.outpost&&!choiceSet.has(c.id)&&((c.id*13)%17===0)){line(p.x-3,p.y+4,p.x-5,p.y,colors.dark+'77');line(p.x-2,p.y+4,p.x+1,p.y-2,colors.dark+'77');}
 if(choiceSet.has(c.id)){const offer=c.id===selected?selectedType(c):c.offer;ctx.save();poly(p.x,p.y,R-4);ctx.strokeStyle=c.id===selected?'#fffde5':'#fff9dfbd';ctx.lineWidth=c.id===selected?2.8:1.3;ctx.setLineDash(c.id===selected?[]:[3,3]);ctx.stroke();ctx.restore();offerIcon(offer,p.x,p.y-6);roundRect(p.x-17,p.y+5,34,13,4,state.gold[0]>=E.TYPES[offer].cost?'#fff0bfe8':'#685548e8');label('◆ '+E.TYPES[offer].cost,p.x,p.y+11.5,9,state.gold[0]>=E.TYPES[offer].cost?'#394a2b':'#ffe3bc');}
 }
 drawFrontier();
 for(const c of state.cells)if(c.outpost)outpost(c);
 for(const c of state.cells)if(c.building)building(c);
 state.units.slice().sort((a,b)=>a.y-b.y).forEach(troop);
 drawAim();drawWeaponEffects();
 if(selected!==null&&state.cells[selected]){const c=state.cells[selected],p=point(c);ctx.save();poly(p.x,p.y,R+1);ctx.lineWidth=2;ctx.strokeStyle='#fff8ce';ctx.shadowColor='#fff1b4';ctx.shadowBlur=9;ctx.stroke();ctx.restore();}
 for(const p of particles){const t=(performance.now()-p.birth)/650;if(t>=1)continue;ctx.globalAlpha=1-t;label(p.text,p.x,p.y-t*22,12,p.color);ctx.globalAlpha=1;}
 particles=particles.filter(p=>performance.now()-p.birth<650);
}
function toast(text){$('toast').textContent=text;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),2600);}
function beep(freq=600,length=.08){if(!sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+length);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+length);}catch{sound=false;}}
function updateStandings(){const all=state.sides.map(f=>({f,stats:E.stats(state,f.id)})),total=state.cells.filter(c=>!c.water).length,neutralLand=state.cells.filter(c=>!c.water&&c.owner===-1).length;
 $('standings').style.setProperty('--faction-count',all.length);
 const standingKey=all.map(({f,stats:a})=>`${f.id}:${a.land}:${a.units}:${a.alive}`).join('|');
 if($('standings').dataset.key!==standingKey){$('standings').dataset.key=standingKey;$('standings').replaceChildren(...all.map(({f,stats:a})=>{const card=document.createElement('div');card.className='faction-card'+(!a.alive?' eliminated':'');card.style.setProperty('--faction',palette(f.id).light);const title=document.createElement('strong');title.textContent=shortName(f.id)+(f.id===0?'·你':'');card.title=`${f.name} · ${a.land} 格 · ${a.units} 军队${a.alive?'':' · 已淘汰'}`;const data=document.createElement('span');data.className='faction-stat';const count=document.createElement('b');count.textContent=a.land;data.append(count,document.createTextNode(a.alive?'格':' · 已淘汰'));card.append(title,data);return card;}));}
 const meterKey=all.map(({stats:a})=>a.land).join('|')+'|'+neutralLand;
 if($('territoryMeter').dataset.key!==meterKey){$('territoryMeter').dataset.key=meterKey;const pieces=all.map(({f,stats:a})=>({name:f.name,land:a.land,color:palette(f.id).color}));if(neutralLand)pieces.push({name:'中立',land:neutralLand,color:neutral.color});$('territoryMeter').replaceChildren(...pieces.map(p=>{const n=document.createElement('span');n.style.width=(p.land/total*100)+'%';n.style.background=p.color;n.title=`${p.name} ${p.land} 格`;return n;}));$('territoryMeter').setAttribute('aria-label',pieces.map(p=>`${p.name} ${p.land} 格`).join('，'));}
}
function updateUpgrades(){for(const key of Object.keys(E.UPGRADES)){const spec=E.UPGRADES[key],button=$('upgrade-'+key),level=state.upgrades[0][key],cost=E.upgradeCost(state,key);button.disabled=state.phase!=='playing'||!!aim||cost===null||state.gold[0]<cost;button.classList.toggle('maxed',cost===null);button.querySelector('.upgrade-level').textContent=level+'/'+spec.max;button.querySelector('.upgrade-cost').textContent=cost===null?'已满级':state.gold[0]<cost?`还差 ${Math.ceil(cost-state.gold[0])} 金`:`◆ ${cost} 升级`;button.setAttribute('aria-label',`${spec.name}，${level}/${spec.max} 级，${spec.description}，${cost===null?'已满级':cost+' 金币'}`);}}
function displayNumber(value){return String(Number(Number(value).toFixed(2)));}
function selectedType(c){return selectedBuildType&&E.TYPES[selectedBuildType]?selectedBuildType:c.offer;}
function updateSelection(){const c=selected!==null?state.cells[selected]:null,buildable=c&&E.available(state,0).some(t=>t.id===c.id);let title='点击虚线地块',description='格上有图标与价格。先选地，再建造。',icon='⌖',action='选择\n地块',disabled=true;
 if(c){const owner=c.owner===0?'金曜 · 你':c.owner<0?'中立':shortName(c.owner)+' · AI';if(c.water){icon='≈';title='水域 · 无法通行';description='部队会自动选择陆路，守住狭窄路口。';action='水域';}
 else if(c.outpost){icon=c.outpost==='gold'?'◆':'⚑';title=`${owner} · ${c.outpost==='gold'?'金哨据点':'集结据点'}`;description=(c.outpost==='gold'?'占领后每秒 +2 金。':'占领后训练速度 +12%。')+'部队经过即可占领，这里不能建造。';action='部队\n占领';}
 else if(c.building){const type=c.building.type,branch=E.BUILDING_UPGRADES?.[type]?.[c.building.branch];icon=icons[type];title=`${owner} · ${E.TYPES[type].name} Lv.${c.building.level||1}`;description=`${branch?branch.name+' · ':''}${shortDescriptions[type]} 耐久 ${Math.ceil(c.building.hp)}/${Math.ceil(c.building.maxHp)}`;action=c.owner===0?'已建造':'敌方\n建筑';}
 else{const type=selectedType(c);icon=icons[type]||'⌖';title=`${E.TYPES[type].name} · 第 ${c.r+1} 排`;description=buildable?(state.gold[0]<E.TYPES[type].cost?`还差 ${Math.ceil(E.TYPES[type].cost-state.gold[0])} 金。`:'')+shortDescriptions[type]:c.owner===0?'先建造相邻地块，与主城保持连接。':`${owner}领地，军队经过空地即可占领。`;action=state.gold[0]<E.TYPES[type].cost?`还差\n${Math.ceil(E.TYPES[type].cost-state.gold[0])} 金`:`建造\n◆ ${E.TYPES[type].cost}`;disabled=!buildable||state.phase!=='playing'||state.gold[0]<E.TYPES[type].cost;}}
 $('contextLabel').textContent=aim?'武器瞄准':activePanel==='route'?'发展路线':activePanel==='tech'?'王国科技':buildable?'选中空地':c?.building?.side===0?'选中建筑':'战场指挥';$('selectionIcon').textContent=icon;$('selectionTitle').textContent=title;$('selectionDescription').textContent=description;$('build').textContent=action;$('build').disabled=disabled||!!aim;
 const choices=state.phase==='playing'?E.available(state,0):[],key=choices.map(c=>`${c.id}:${c.id===selected}:${state.gold[0]>=E.TYPES[c.offer].cost}`).join('|')+'|'+!!aim;if($('quickBuilds').dataset.key!==key){$('quickBuilds').dataset.key=key;$('quickBuilds').replaceChildren(...choices.map(c=>{const b=document.createElement('button');b.textContent=`${icons[c.offer]} ${E.TYPES[c.offer].name} ${E.TYPES[c.offer].cost}`;b.disabled=!!aim;b.setAttribute('aria-label',`选择第 ${c.r+1} 排第 ${c.c+1} 列的${E.TYPES[c.offer].name}，${E.TYPES[c.offer].cost} 金币`);b.setAttribute('aria-pressed',String(c.id===selected));b.classList.toggle('selected',c.id===selected);b.addEventListener('click',()=>select(c.id));return b;}));if(!choices.length&&state.phase==='playing'){const note=document.createElement('span');note.className='empty-builds';note.textContent='暂无相连空地，等部队占领后继续扩建';$('quickBuilds').append(note);}}
 $('catalogPanel').classList.toggle('hidden',!buildable||!!aim);$('quickSection').classList.toggle('hidden',!!buildable||!!(c?.building?.side===0&&c.building.type!=='castle')); $('toggleQuick').disabled=!!aim;
 updateCatalog(c,buildable);updateBuilding(c);updateRoutes();updateAim();updateDecision();
}
function detailButton(id,title,description,action){const b=document.createElement('button');b.id=id;b.className='detail-button';const heading=document.createElement('strong');heading.textContent=title;const desc=document.createElement('span');desc.className='detail-description';desc.textContent=description;const foot=document.createElement('span');foot.className='detail-cost';foot.textContent=action;b.append(heading,desc,foot);return b;}
function updateCatalog(c,buildable){if(!buildable)return;const types=Object.keys(E.TYPES).filter(k=>k!=='castle'&&k!=='mystery'),key=c.id+':'+selectedBuildType+':'+types.map(k=>state.gold[0]>=E.TYPES[k].cost).join(',');if($('buildingCatalog').dataset.key===key)return;$('buildingCatalog').dataset.key=key;const normal=detailButton('catalog-default','↻ 地块默认',E.TYPES[c.offer].name,`◆ ${E.TYPES[c.offer].cost}`);normal.classList.toggle('selected',selectedBuildType===null);normal.setAttribute('aria-pressed',String(selectedBuildType===null));normal.onclick=()=>{selectedBuildType=null;updateUI();draw();};const buttons=types.map(type=>{const spec=E.TYPES[type],b=detailButton('catalog-'+type,icons[type]+' '+spec.name,spec.description,`◆ ${spec.cost}`);b.classList.toggle('selected',type===selectedBuildType);b.classList.toggle('unaffordable',state.gold[0]<spec.cost);b.setAttribute('aria-pressed',String(type===selectedBuildType));b.onclick=()=>{if(aim||state.phase!=='playing')return;selectedBuildType=type;updateUI();draw();};return b;});$('buildingCatalog').replaceChildren(normal,...buttons);}
function updateBuilding(c){const own=c&&c.owner===0&&c.building?.side===0,b=own?c.building:null,branches=b?E.BUILDING_UPGRADES?.[b.type]:null;$('buildingPanel').classList.toggle('hidden',!branches);$('weaponPanel').classList.toggle('hidden',!own||b.type!=='arsenal');
 if(branches){$('buildingLevel').textContent=`Lv.${b.level||1} / 3`;const key=c.id+':'+b.type+':'+b.level+':'+b.branch; if($('buildingUpgrades').dataset.key!==key){$('buildingUpgrades').dataset.key=key;$('buildingUpgrades').replaceChildren(...Object.entries(branches).map(([k,spec])=>{const button=detailButton('branch-'+k,spec.name,spec.description,'');button.onclick=()=>previewDecision('branch',k);return button;}));}for(const [k,spec]of Object.entries(branches)){const button=$('branch-'+k),locked=!!b.branch&&b.branch!==k,cost=E.buildingUpgradeCost(state,c.id,k,0);button.disabled=state.phase!=='playing'||!!aim||locked||cost===null;button.classList.toggle('selected',b.branch===k);button.classList.toggle('locked',locked);button.querySelector('.detail-cost').textContent=locked?'互斥分支 · 已锁定':cost===null?'Lv.3 · 已满级':state.gold[0]<cost?`◆ ${cost} · 还差 ${Math.ceil(cost-state.gold[0])} 金`:`◆ ${cost} · 预览 Lv.${(b.level||1)+1}`;button.setAttribute('aria-label',`${spec.name}，${spec.description}，${button.querySelector('.detail-cost').textContent}`);}}
 if(own&&b.type==='arsenal'){for(const k of Object.keys(E.WEAPONS)){const spec=E.WEAPONS[k],status=E.weaponStatus(state,c.id,k,0),button=$('weapon-'+k);button.disabled=state.phase!=='playing'||!!aim;button.classList.toggle('waiting',!status.ok);button.querySelector('.detail-cost').textContent=`◆ ${status.cost} / ${status.ammoCost} 弹 · 射程 ${status.range} 格`;button.querySelector('.weapon-readiness').textContent=status.ok?'选择武器 → 瞄准':status.reason+' · 可先预览';}const status=E.weaponStatus(state,c.id,'barrage',0),interval=18-(b.branch==='magazine'?3*((b.level||1)-1):0);$('arsenalStock').textContent=`弹药 ${status.ammo}/${status.maxAmmo} · ${status.cooldown>0?'冷却 '+Math.ceil(status.cooldown)+'秒':status.ammo<status.maxAmmo?Math.max(1,Math.ceil(interval-(b.ammoTimer||0)))+'秒补弹':'已装满'}`;}
}
function updateRoutes(){if(!E.ROUTES)return;const route=state.routes[0],cost=E.routeCost(state,0);$('routeSummary').textContent=route.key?`${E.ROUTES[route.key].name} · ${route.level}/2 级`:'经济 / 防御 / 进攻，三选一';for(const [key,spec]of Object.entries(E.ROUTES)){const b=$('route-'+key),locked=!!route.key&&route.key!==key;b.disabled=state.phase!=='playing'||!!aim||locked||cost===null;b.classList.toggle('selected',route.key===key);b.classList.toggle('locked',locked);b.querySelector('.detail-cost').textContent=locked?'本局已锁定其他路线':cost===null?'2/2 级 · 已满级':state.gold[0]<cost?`◆ ${cost} · 还差 ${Math.ceil(cost-state.gold[0])} 金`:route.key?`◆ ${cost} · 预览 2 级`:`◆ ${cost} · 预览路线`;}}
function upgradeSelectedBuilding(branch){if(aim||selected===null)return;const result=E.upgradeBuilding(state,selected,branch,0);if(!result.ok){toast(result.reason);return;}toast(`${E.BUILDING_UPGRADES[state.cells[selected].building.type][branch].name} · 升至 ${result.level} 级`);beep(740,.12);updateUI();draw();}
function chooseRoute(key){if(aim)return;const result=state.routes[0].key?E.upgradeRoute(state,0):E.chooseRoute(state,key,0);if(!result.ok){toast(result.reason);return;}toast(`${E.ROUTES[key].name} · ${state.routes[0].level} 级`);beep(680,.12);updateUI();}
function clearDecision(){decision=null;$('decisionPanel').classList.add('hidden');$('commandPanel').classList.remove('has-decision');$('confirmDecision').disabled=true;}
function decisionValid(){if(!decision||state.phase!=='playing'||aim)return false;if(decision.kind==='route'){const route=state.routes[0];return route.key===decision.routeKey&&route.level===decision.level;}const c=state.cells[decision.source];return selected===decision.source&&c?.owner===0&&c.building===decision.building&&c.building.side===0&&c.building.level===decision.level&&c.building.hp>0;}
function previewDecision(kind,key){if(state.phase!=='playing'||aim)return;clearDecision();if(kind==='branch'){const c=state.cells[selected];if(!c?.building||c.building.side!==0)return;decision={kind,key,source:c.id,building:c.building,level:c.building.level};}else{decision={kind,key,routeKey:state.routes[0].key,level:state.routes[0].level};}setTray(true);updateDecision();layoutBoard();}
function updateDecision(){if(!decision)return;if(!decisionValid()){clearDecision();return;}const spec=decision.kind==='route'?E.ROUTES[decision.key]:E.BUILDING_UPGRADES[decision.building.type][decision.key],cost=decision.kind==='route'?E.routeCost(state,0):E.buildingUpgradeCost(state,decision.source,decision.key,0);if(cost===null){clearDecision();return;}const first=decision.kind==='route'?!decision.routeKey:!decision.building.branch;$('decisionPanel').classList.remove('hidden');$('commandPanel').classList.add('has-decision');$('decisionTitle').textContent=spec.name+' · '+(decision.kind==='route'?'路线':'建筑分支');$('decisionDescription').textContent=spec.description+(first?' 确认后锁定，其他'+(decision.kind==='route'?'路线':'分支')+'将不可选。':'')+(decision.kind==='branch'?' 本次另加基础耐久的 25%。':'');$('decisionCost').textContent=`◆ ${cost} · 升至 ${decision.level+1} 级`+(state.gold[0]<cost?` · 还差 ${Math.ceil(cost-state.gold[0])} 金`:'');$('confirmDecision').textContent=first?'确认选择':'确认升级';$('confirmDecision').disabled=state.gold[0]<cost;}
function confirmDecision(){if(!decisionValid()){clearDecision();return;}const choice=decision;clearDecision();if(choice.kind==='route')chooseRoute(choice.key);else upgradeSelectedBuilding(choice.key);layoutBoard();}
function setPanel(key){if(aim)return;if(activePanel!==key)clearDecision();activePanel=key;for(const tab of ['manage','route','tech']){$('tab-'+tab).classList.toggle('active',tab===key);$('tab-'+tab).setAttribute('aria-selected',String(tab===key));$('panel-'+tab).classList.toggle('hidden',tab!==key);}setTray(key!=='manage'||!compactScreen());$('contextLabel').textContent=key==='route'?'发展路线':key==='tech'?'王国科技':'战场指挥';layoutBoard();}
function clearAim(){aim=null;$('commandPanel').classList.remove('is-aiming');$('aimPanel').classList.add('hidden');$('aimRibbon').classList.add('hidden');$('battlefield').classList.remove('is-aiming');$('confirmFire').disabled=true;}
function validAim(){if(!aim)return false;const c=state.cells[aim.source];return state.phase==='playing'&&c?.owner===0&&c.building===aim.building&&c.building.side===0&&c.building.type==='arsenal'&&c.building.hp>0;}
function beginAim(key){const c=selected!==null?state.cells[selected]:null;if(state.phase!=='playing'||!c||c.owner!==0||c.building?.side!==0||c.building.type!=='arsenal')return;clearDecision();resetGesture();setPanel('manage');aim={source:c.id,building:c.building,weapon:key,target:null,preview:null};updateUI();draw();layoutBoard();canvas.focus({preventScroll:true});}
function selectAimTarget(id){if(!validAim()){clearAim();updateUI();return;}aim.target=id;updateUI();draw();}
function updateAim(){if(!aim)return;if(!validAim()){clearAim();toast('瞄准已取消：军械库不可用');return;}const spec=E.WEAPONS[aim.weapon],status=E.weaponStatus(state,aim.source,aim.weapon,0);aim.preview=aim.target===null?null:E.previewWeapon(state,aim.source,aim.weapon,aim.target,0);$('aimPanel').classList.remove('hidden');$('commandPanel').classList.add('is-aiming');$('aimRibbon').classList.remove('hidden');$('battlefield').classList.add('is-aiming');$('aimTitle').textContent=`⌖ ${spec.name} · ${aim.target===null?'请选择目标':'第 '+(state.cells[aim.target].r+1)+' 排 / '+(state.cells[aim.target].c+1)+' 列'}`;
 const currentDamage=aim.preview||E.previewWeapon(state,aim.source,aim.weapon,aim.source,0),damageText=`本次伤害：部队 ${displayNumber(currentDamage.damage)} / 建筑 ${displayNumber(currentDamage.buildingDamage)}`,resource=`◆ ${status.cost} · ${status.ammoCost} 弹（库存 ${status.ammo}/${status.maxAmmo}） · 射程 ${status.range} 格`,ready=aim.preview?.ok;const geometry=aim.preview?.cells?.length?`覆盖 ${aim.preview.cells.length} 格，`:'';const hint=aim.target===null?'点击地图查看范围，二次点击也不会发射。':ready?`${geometry}已锁定预览。点击“确认开火”射击。`:aim.preview.reason;$('aimDescription').textContent=resource+'\n'+damageText+(aim.weapon==='rail'?' · 沿方向穿透至射程终点':' · 爆炸半径 '+currentDamage.radius+' 格')+'\n'+hint;$('confirmFire').disabled=!ready;$('confirmFire').textContent=ready?`确认开火 · ◆ ${status.cost}`:'确认开火';$('confirmFire').setAttribute('aria-label',ready?`确认向第${state.cells[aim.target].r+1}排第${state.cells[aim.target].c+1}列开火，消耗${status.cost}金币和${status.ammoCost}发弹药，不伤友军`:'请先选择有效目标');}
function confirmFire(){if(!validAim()){clearAim();updateUI();return;}if(aim.target===null)return;const shot={...aim},preview=E.previewWeapon(state,shot.source,shot.weapon,shot.target,0),result=E.fireWeapon(state,shot.source,shot.weapon,shot.target,0);if(!result.ok){toast(result.reason);updateUI();return;}weaponEffects.push({kind:shot.weapon,source:shot.source,target:shot.target,cells:preview.cells||[],line:preview.line,radius:preview.radius,birth:performance.now()});const p=point(state.cells[shot.target]);particles.push({x:p.x,y:p.y-20,text:shot.weapon==='rail'?'穿透发射！':'重炮轰击！',color:'#fff1a5',birth:performance.now()});clearAim();toast(`${E.WEAPONS[shot.weapon].name}已发射 · 友军安全`);beep(shot.weapon==='rail'?180:110,.25);updateUI();draw();}
function drawAim(){if(!aim||!validAim())return;const source=point(state.cells[aim.source]),status=E.weaponStatus(state,aim.source,aim.weapon,0);ctx.save();ctx.beginPath();ctx.arc(source.x,source.y,status.range*S,0,Math.PI*2);ctx.strokeStyle='#fff2bb90';ctx.lineWidth=1.5;ctx.setLineDash([5,5]);ctx.stroke();ctx.setLineDash([]);ellipse(source.x,source.y,7,7,'#fff2a9cc');if(aim.preview){for(const id of aim.preview.cells||[]){const c=state.cells[id];if(!c)continue;const p=point(c);poly(p.x,p.y,R-2);ctx.fillStyle=aim.preview.ok?'#ff8a474f':'#e1c79935';ctx.fill();ctx.strokeStyle=aim.preview.ok?'#fff1ae':'#e4ba98';ctx.lineWidth=1.5;ctx.stroke();}if(aim.preview.line){const l=aim.preview.line;line(OX+l.from.x*S,OY+l.from.y*S,OX+l.to.x*S,OY+l.to.y*S,'#ffecae99',Math.max(2,l.width*S*2));line(OX+l.from.x*S,OY+l.from.y*S,OX+l.to.x*S,OY+l.to.y*S,'#fff5d7',2);}if(aim.target!==null){const t=point(state.cells[aim.target]);if(aim.preview.radius){ctx.beginPath();ctx.arc(t.x,t.y,aim.preview.radius*S,0,Math.PI*2);ctx.strokeStyle='#ffe6a5bb';ctx.lineWidth=2;ctx.setLineDash([5,3]);ctx.stroke();ctx.setLineDash([]);}ctx.beginPath();ctx.arc(t.x,t.y,15,0,Math.PI*2);ctx.strokeStyle='#fffbe0';ctx.lineWidth=2;ctx.stroke();line(t.x-22,t.y,t.x-9,t.y,'#fffbe0',2);line(t.x+9,t.y,t.x+22,t.y,'#fffbe0',2);line(t.x,t.y-22,t.x,t.y-9,'#fffbe0',2);line(t.x,t.y+9,t.x,t.y+22,'#fffbe0',2);}}ctx.restore();}
function drawWeaponEffects(){const now=performance.now();weaponEffects=weaponEffects.filter(f=>now-f.birth<1100);for(const effect of weaponEffects){const t=(now-effect.birth)/1100,source=point(state.cells[effect.source]),target=point(state.cells[effect.target]);ctx.save();ctx.globalAlpha=1-t;if(effect.kind==='rail'&&effect.line){const l=effect.line;line(OX+l.from.x*S,OY+l.from.y*S,OX+l.to.x*S,OY+l.to.y*S,'#ffad4b',18*(1-t)+2);line(OX+l.from.x*S,OY+l.from.y*S,OX+l.to.x*S,OY+l.to.y*S,'#fff9d7',5*(1-t)+1);}else{line(source.x,source.y,target.x,target.y,'#f5de9b88',2);ctx.beginPath();ctx.arc(target.x,target.y,8+t*R*2.5,0,Math.PI*2);ctx.fillStyle='#ffb94666';ctx.fill();ctx.strokeStyle='#fff0ab';ctx.lineWidth=6*(1-t)+1;ctx.stroke();}for(const id of effect.cells){const p=point(state.cells[id]);ellipse(p.x+Math.sin(id)*t*15,p.y-t*24,3*(1-t)+1,3*(1-t)+1,'#fff4ba');}ctx.restore();}}
function setupArsenal(){for(const [key,spec]of Object.entries(E.ROUTES||{})){const summaries={economy:'每级 +25% 收入；−10% 直接伤害',defense:'每级 +30% 建筑耐久、+20% 城防攻击；−10% 训练',offense:'每级 +20% 伤害、+10% 训练；−10% 收入'};const b=detailButton('route-'+key,spec.name,summaries[key]||spec.description,'');b.onclick=()=>previewDecision('route',key);$('routes').append(b);}for(const [key,spec]of Object.entries(E.WEAPONS||{})){const b=detailButton('weapon-'+key,spec.name,(key==='rail'?`沿目标方向贯穿至射程终点，两侧各 ${spec.width} 格。`:`以目标为中心，半径 ${spec.radius} 格的范围爆炸。`)+` 共享冷却 ${spec.cooldown} 秒。`,''),ready=document.createElement('span');ready.className='weapon-readiness';b.append(ready);b.onclick=()=>beginAim(key);$('weapons').append(b);}for(const key of ['manage','route','tech'])$('tab-'+key).onclick=()=>setPanel(key);$('confirmDecision').onclick=confirmDecision;$('cancelDecision').onclick=()=>{clearDecision();layoutBoard();};$('toggleTray').onclick=()=>{clearDecision();setTray($('toggleTray').getAttribute('aria-expanded')!=='true');};$('zoom').onclick=()=>setZoom(!zoomed);$('toggleCatalog').onclick=()=>toggleDisclosure('toggleCatalog','buildingCatalog','类型');$('toggleQuick').onclick=()=>toggleDisclosure('toggleQuick','quickBuilds','可建空地');$('cancelAim').onclick=()=>{clearAim();updateUI();draw();};$('confirmFire').onclick=confirmFire;}
function toggleDisclosure(button,panel,title){const expanded=$(button).getAttribute('aria-expanded')!=='true';$(button).setAttribute('aria-expanded',String(expanded));$(button).textContent=button==='toggleCatalog'?(expanded?'收起':'展开'):title+(expanded?'　收起':'　展开');$(panel).classList.toggle('hidden',!expanded);layoutBoard();}
function updateUI(){if(aim&&!validAim()){clearAim();if(state.phase==='playing')toast('军械库已失去，瞄准已取消');}const a=E.stats(state,0);$('gold').textContent=a.gold;$('income').textContent=`+${displayNumber(a.income)} / 秒`;$('units').textContent=a.units;$('outposts').textContent=a.outposts;updateStandings();updateUpgrades();updateSelection();
 const time=Math.max(0,Math.ceil(E.DURATION-state.elapsed));$('clock').textContent=`${String(Math.floor(time/60)).padStart(2,'0')}:${String(time%60).padStart(2,'0')}`;$('phaseLabel').textContent=state.phase==='ready'?'准备出征':state.phase==='paused'?'战场暂停':state.phase==='over'?'战斗结束':`${state.alive.filter(Boolean).length} 方存活`;
 $('matchMode').textContent=E.MODES[state.mode].name;$('mapName').textContent=E.MAPS[state.map].name;$('seedBadge').textContent='#'+state.seed;
 $('pause').disabled=!['playing','paused'].includes(state.phase);$('speed').disabled=!['playing','paused'].includes(state.phase);$('commandPanel').classList.toggle('is-preview',state.phase==='ready');$('gameShell').classList.toggle('is-ready',state.phase==='ready');
 const target=selected!==null?state.cells[selected]:null,canBuild=target&&E.available(state,0).some(c=>c.id===target.id);
 const hasMine=state.cells.some(c=>c.building?.side===0&&c.building.type==='mine'),hasArmy=state.cells.some(c=>c.building?.side===0&&UNITTYPE(c.building.type));$('hint').textContent=aim?'瞄准中 · 点击地图仅预览，确认按钮才开火':canBuild?`再点此格建造 · ◆ ${E.TYPES[selectedType(target)].cost}`:!hasMine?'你是金曜 · 先建金矿，持续获得金币':!hasArmy?'建设兵营，部队会自动出征':time<30?'最后冲刺！时间到比较存活势力领地':state.classic?'绕湖推进 · 守住主城，继续扩建':'灰色为中立 · 金哨加收入，集结加训练';
 if(state.phase==='over'&&$('result').classList.contains('hidden'))showResult();layoutBoard();
}
function select(id){if(aim){selectAimTarget(id);return;}clearDecision();if(selected!==id){selectedBuildType=null;$('buildingCatalog').classList.remove('hidden');$('toggleCatalog').setAttribute('aria-expanded','true');$('toggleCatalog').textContent='收起';}selected=id;setPanel('manage');updateUI();draw();}
function buy(){if(aim||selected===null)return;const c=state.cells[selected],requested=selectedBuildType,result=E.purchase(state,selected,0,requested);if(!result.ok){toast(result.reason);return;}const p=point(c);particles.push({x:p.x,y:p.y-20,text:`−${result.cost}`,color:'#fff4a1',birth:performance.now()});beep(result.type==='knight'?880:520,.12);selectedBuildType=null;toast(!requested&&c.offer==='mystery'?`盲盒揭晓：${E.TYPES[result.type].name}！`:`${E.TYPES[result.type].name}建造完成`);updateUI();draw();}
function upgrade(key){if(aim)return;const result=E.upgrade(state,key,0);if(!result.ok){toast(result.reason);return;}toast(`${E.UPGRADES[key].name}升至 ${result.level} 级`);beep(740,.12);updateUI();}
function freshSeed(){return Math.floor(Math.random()*2147483646)+1;}
function readSeed(){const raw=$('seedInput').value.trim();if(!/^\d{1,10}$/.test(raw)||Number(raw)>4294967295){toast('请输入 0 到 4294967295 之间的整数种子');$('seedInput').setAttribute('aria-invalid','true');return false;}$('seedInput').setAttribute('aria-invalid','false');seed=Number(raw);$('seedInput').value=String(seed);return true;}
function preparePreview(){if(state.phase!=='ready')return;resetGesture();clearDecision();state=E.create(seed,difficulty,{mode,map});selected=null;selectedBuildType=null;clearAim();particles=[];weaponEffects=[];updateUI();draw();}
function start(replay=false,newSeed=false){resetGesture();clearDecision();clearAim();setPanel('manage');setZoom(false);if(replay){seed=newSeed?freshSeed():state.seed;difficulty=state.difficulty;mode=state.mode;map=state.map;}else if(!readSeed())return;state=E.create(seed,difficulty,{mode,map});state.phase='playing';selected=null;selectedBuildType=null;clearAim();particles=[];weaponEffects=[];previousAlive=state.alive.slice();speed=1;$('speed').textContent='1×';$('opening').classList.add('hidden');$('battlefield').classList.remove('menu-open');$('result').classList.add('hidden');$('pauseOverlay').classList.add('hidden');$('pause').textContent='Ⅱ';$('pause').setAttribute('aria-label','暂停游戏');last=performance.now();updateUI();resize();beep(440,.1);layoutBoard();canvas.focus({preventScroll:true});}
function pause(){resetGesture();clearDecision();clearAim();if(state.phase==='playing'){state.phase='paused';$('pauseOverlay').classList.remove('hidden');$('pauseDetails').textContent=`${E.MODES[state.mode].name} · ${E.MAPS[state.map].name} · #${state.seed}`;$('pause').textContent='▷';$('pause').setAttribute('aria-label','继续游戏');}else if(state.phase==='paused'){state.phase='playing';$('pauseOverlay').classList.add('hidden');$('pause').textContent='Ⅱ';$('pause').setAttribute('aria-label','暂停游戏');last=performance.now();}updateUI();}
function menu(){resetGesture();clearDecision();clearAim();setPanel('manage');setZoom(false);seed=state.seed;mode=state.mode;map=state.map;difficulty=state.difficulty;state=E.create(seed,difficulty,{mode,map});selected=null;selectedBuildType=null;clearAim();particles=[];weaponEffects=[];previousAlive=state.alive.slice();$('seedInput').value=String(seed);$('seedInput').setAttribute('aria-invalid','false');$('mapSelect').value=map;$('result').classList.add('hidden');$('pauseOverlay').classList.add('hidden');$('opening').classList.remove('hidden');$('battlefield').classList.add('menu-open');updateUI();draw();layoutBoard();$('start').focus({preventScroll:true});}
function showResult(){resetGesture();clearDecision();clearAim();const win=state.winner===0,draw=state.winner===null&&((state.resultKind==='timeout'&&state.tiedSides.includes(0))||state.resultKind==='draw'),winner=state.winner===null?'':shortName(state.winner);$('resultIcon').textContent=draw?'⚑':win?'♛':'♜';$('resultKicker').textContent=draw?'DRAW':win?'VICTORY':'TRY AGAIN';$('resultTitle').textContent=draw?'金曜并列第一！':win?'金曜凯旋！':state.resultKind==='timeout'?(winner?`${winner}领地领先`:'这次，未能夺冠'):'金曜主城失守';$('resultReason').textContent=state.reason;$('resultLand').textContent=E.stats(state,0).land;$('resultBuilds').textContent=state.builds[0];$('resultKills').textContent=state.kills[0];$('resultSeed').textContent=`${E.MODES[state.mode].name} · ${E.MAPS[state.map].name} · 种子 ${state.seed}`;$('result').classList.remove('hidden');$('again').focus({preventScroll:true});beep(win?784:240,.25);}
function openDialog(id){resetGesture();clearDecision();clearAim();wasPlaying=state.phase==='playing';if(wasPlaying)pause();$(id).showModal();}
function setupUpgrades(){for(const key of Object.keys(E.UPGRADES)){const spec=E.UPGRADES[key],b=document.createElement('button');b.id='upgrade-'+key;b.className='upgrade-button';const level=document.createElement('span');level.className='upgrade-level';const title=document.createElement('strong');title.textContent=spec.name;const description=document.createElement('span');description.className='upgrade-description';description.textContent=spec.description;const cost=document.createElement('span');cost.className='upgrade-cost';b.append(level,title,description,cost);b.addEventListener('click',()=>upgrade(key));$('upgrades').append(b);}}
function hitCell(e){const rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height||e.clientX<rect.left||e.clientY<rect.top||e.clientX>rect.left+rect.width||e.clientY>rect.top+rect.height)return null;const x=(e.clientX-rect.left)/rect.width*W,y=(e.clientY-rect.top)/rect.height*H;let nearest=null,dist=Infinity;for(const c of state.cells){const p=point(c),d=Math.hypot(x-p.x,y-p.y);if(d<dist){dist=d;nearest=c;}}return nearest&&dist<=R?nearest:null;}
canvas.addEventListener('pointerdown',e=>{if(e.isPrimary===false||e.button>0){resetGesture();return;}if(state.phase!=='playing')return;const c=hitCell(e),view=$('boardViewport');gesture=c?{pointerId:e.pointerId,x:e.clientX,y:e.clientY,cell:c.id,state,dragged:false,scrollX:view.scrollLeft||0,scrollY:view.scrollTop||0}:null;});
canvas.addEventListener('pointermove',e=>{if(!gesture||e.pointerId!==gesture.pointerId)return;const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(Math.hypot(dx,dy)>10)gesture.dragged=true;if(gesture.dragged&&zoomed){$('battlefield').classList.add('is-dragging');if(e.pointerType==='mouse'){const view=$('boardViewport');view.scrollLeft=gesture.scrollX-dx;view.scrollTop=gesture.scrollY-dy;e.preventDefault?.();}}});
canvas.addEventListener('pointerup',e=>{const down=gesture;resetGesture();if(!down||e.pointerId!==down.pointerId||down.dragged||Math.hypot(e.clientX-down.x,e.clientY-down.y)>10||state!==down.state||state.phase!=='playing'||e.isPrimary===false||e.button>0)return;const nearest=hitCell(e);if(!nearest||nearest.id!==down.cell)return;if(aim){selectAimTarget(nearest.id);return;}if(selected===nearest.id&&E.available(state,0).some(c=>c.id===nearest.id))buy();else select(nearest.id);});
canvas.addEventListener('pointercancel',resetGesture);canvas.addEventListener('pointerleave',resetGesture);
canvas.addEventListener('keydown',e=>{if(e.key==='Escape'&&aim){e.preventDefault();clearAim();updateUI();draw();return;}if(state.phase!=='playing')return;const base=state.cells.find(c=>c.building?.type==='castle'&&c.building.side===0);if(!base)return;const c=state.cells[aim?(aim.target??aim.source):(selected??base.id)];if(e.key==='Enter'){e.preventDefault();if(aim){selectAimTarget(aim.target??aim.source);toast('目标已预览，请点击“确认开火”按钮发射');return;}if(e.repeat)return;if(selected===null)select(E.available(state,0)[0]?.id??base.id);else buy();return;}const offsets={ArrowLeft:-1,ArrowRight:1,ArrowUp:-E.COLS,ArrowDown:E.COLS};if(e.key in offsets){e.preventDefault();const next=Math.max(0,Math.min(state.cells.length-1,c.id+offsets[e.key]));if(aim)selectAimTarget(next);else select(next);}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&decision){e.preventDefault();clearDecision();layoutBoard();return;}if(e.key==='Escape'&&aim){e.preventDefault();clearAim();updateUI();draw();return;}if(e.code==='Space'&&!document.querySelector('dialog[open]')&&!['BUTTON','INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();pause();}});
$('start').onclick=()=>start();$('build').onclick=buy;$('pause').onclick=pause;$('resume').onclick=pause;$('restartPause').onclick=()=>start(true);$('again').onclick=()=>start(true);$('newRound').onclick=()=>start(true,true);$('menu').onclick=menu;$('pauseMenu').onclick=menu;
$('speed').onclick=()=>{speed=speed===1?2:1;$('speed').textContent=speed+'×';};$('sound').onclick=()=>{sound=!sound;$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'关闭音效':'开启音效');$('sound').style.color=sound?'#e3ee9c':'';if(sound)beep();toast(sound?'音效已开启':'音效已关闭');};$('help').onclick=()=>openDialog('helpDialog');$('provenance').onclick=()=>openDialog('sourceDialog');
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('close',()=>{if(wasPlaying&&state.phase==='paused')pause();wasPlaying=false;}));
document.querySelectorAll('[data-difficulty]').forEach(b=>b.onclick=()=>{if(state.phase!=='ready')return;difficulty=b.dataset.difficulty;document.querySelectorAll('[data-difficulty]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});preparePreview();});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(state.phase!=='ready')return;mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});preparePreview();});
$('mapSelect').onchange=()=>{if(state.phase!=='ready')return;map=$('mapSelect').value;preparePreview();};$('seedInput').onchange=()=>{if(state.phase==='ready'&&readSeed())preparePreview();};$('randomSeed').onclick=()=>{if(state.phase!=='ready')return;seed=freshSeed();$('seedInput').value=String(seed);$('seedInput').setAttribute('aria-invalid','false');preparePreview();};
for(const option of $('mapSelect').options)option.textContent=E.MAPS[option.value].name+' · '+E.MAPS[option.value].description;
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.phase==='playing')pause();});window.addEventListener('resize',resize);if(typeof ResizeObserver!=='undefined')new ResizeObserver(layoutBoard).observe($('boardViewport'));window.addEventListener('blur',resetGesture);
let previousAlive=state.alive.slice();
function checkEliminations(){state.alive.forEach((alive,id)=>{if(!alive&&previousAlive[id]&&id!==0&&state.phase!=='over')toast(`${shortName(id)}主城失守，已被淘汰`);});previousAlive=state.alive.slice();}
function frame(now){const delta=last?Math.min((now-last)/1000,.25):0;last=now;if(state.phase==='playing'){let left=delta*speed;while(left>.0001){const dt=Math.min(left,.05);E.tick(state,dt);left-=dt;}uiTimer+=delta;if(uiTimer>.12){checkEliminations();updateUI();uiTimer=0;}}if(state.phase==='over'&&$('result').classList.contains('hidden'))updateUI();draw();requestAnimationFrame(frame);}
setupUpgrades();setupArsenal();resize();updateUI();requestAnimationFrame(frame);
})();
